// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: skill/v1/skill.proto

package skillv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationSkillServiceCompareSkillVersions = "/api.skill.v1.SkillService/CompareSkillVersions"
const OperationSkillServiceCreateSkill = "/api.skill.v1.SkillService/CreateSkill"
const OperationSkillServiceCreateSkillShare = "/api.skill.v1.SkillService/CreateSkillShare"
const OperationSkillServiceDeleteSkill = "/api.skill.v1.SkillService/DeleteSkill"
const OperationSkillServiceDeleteSkillShare = "/api.skill.v1.SkillService/DeleteSkillShare"
const OperationSkillServiceDownloadCatalogSkillVersion = "/api.skill.v1.SkillService/DownloadCatalogSkillVersion"
const OperationSkillServiceDownloadSkillVersion = "/api.skill.v1.SkillService/DownloadSkillVersion"
const OperationSkillServiceForcePublishSkillVersion = "/api.skill.v1.SkillService/ForcePublishSkillVersion"
const OperationSkillServiceGetCatalogSkill = "/api.skill.v1.SkillService/GetCatalogSkill"
const OperationSkillServiceGetCatalogSkillManifest = "/api.skill.v1.SkillService/GetCatalogSkillManifest"
const OperationSkillServiceGetSkill = "/api.skill.v1.SkillService/GetSkill"
const OperationSkillServiceGetSkillVersion = "/api.skill.v1.SkillService/GetSkillVersion"
const OperationSkillServiceGetSkillVersionFile = "/api.skill.v1.SkillService/GetSkillVersionFile"
const OperationSkillServiceListCatalogSkills = "/api.skill.v1.SkillService/ListCatalogSkills"
const OperationSkillServiceListSkillShares = "/api.skill.v1.SkillService/ListSkillShares"
const OperationSkillServiceListSkillVersionFiles = "/api.skill.v1.SkillService/ListSkillVersionFiles"
const OperationSkillServiceListSkillVersions = "/api.skill.v1.SkillService/ListSkillVersions"
const OperationSkillServiceListSkills = "/api.skill.v1.SkillService/ListSkills"
const OperationSkillServiceOfflineSkillVersion = "/api.skill.v1.SkillService/OfflineSkillVersion"
const OperationSkillServiceOnlineSkillVersion = "/api.skill.v1.SkillService/OnlineSkillVersion"
const OperationSkillServicePublishSkillVersion = "/api.skill.v1.SkillService/PublishSkillVersion"
const OperationSkillServiceSubmitSkillVersion = "/api.skill.v1.SkillService/SubmitSkillVersion"
const OperationSkillServiceUpdateSkill = "/api.skill.v1.SkillService/UpdateSkill"
const OperationSkillServiceUploadSkillPackage = "/api.skill.v1.SkillService/UploadSkillPackage"

type SkillServiceHTTPServer interface {
	// CompareSkillVersions CompareSkillVersions returns SKILL.md and file lists for two versions.
	CompareSkillVersions(context.Context, *CompareSkillVersionsRequest) (*CompareSkillVersionsResponse, error)
	// CreateSkill CreateSkill creates one canonical skill.
	CreateSkill(context.Context, *CreateSkillRequest) (*Skill, error)
	// CreateSkillShare CreateSkillShare grants one user/service/app/agent/workflow access to one Skill.
	CreateSkillShare(context.Context, *CreateSkillShareRequest) (*SkillShare, error)
	// DeleteSkill DeleteSkill soft-deletes one canonical skill by name.
	DeleteSkill(context.Context, *DeleteSkillRequest) (*emptypb.Empty, error)
	// DeleteSkillShare DeleteSkillShare revokes all policy actions for one subject on one Skill.
	DeleteSkillShare(context.Context, *DeleteSkillShareRequest) (*emptypb.Empty, error)
	// DownloadCatalogSkillVersion DownloadCatalogSkillVersion returns the package for a catalog-consumable version.
	DownloadCatalogSkillVersion(context.Context, *DownloadSkillVersionRequest) (*SkillPackageDownload, error)
	// DownloadSkillVersion DownloadSkillVersion returns the version package bytes with cache metadata.
	DownloadSkillVersion(context.Context, *DownloadSkillVersionRequest) (*SkillPackageDownload, error)
	// ForcePublishSkillVersion ForcePublishSkillVersion lets an operator publish without normal submit state.
	ForcePublishSkillVersion(context.Context, *SkillVersionActionRequest) (*SkillVersion, error)
	// GetCatalogSkill GetCatalogSkill returns one skill for Agent/Runtime/Catalog consumers.
	GetCatalogSkill(context.Context, *GetCatalogSkillRequest) (*Skill, error)
	// GetCatalogSkillManifest GetCatalogSkillManifest returns the online version manifest for runtime consumers.
	GetCatalogSkillManifest(context.Context, *GetCatalogSkillManifestRequest) (*SkillManifest, error)
	// GetSkill GetSkill returns one canonical skill by name for management views.
	GetSkill(context.Context, *GetSkillRequest) (*Skill, error)
	// GetSkillVersion GetSkillVersion returns one version metadata record.
	GetSkillVersion(context.Context, *GetSkillVersionRequest) (*SkillVersion, error)
	// GetSkillVersionFile GetSkillVersionFile returns one text or base64-encoded file content.
	GetSkillVersionFile(context.Context, *GetSkillVersionFileRequest) (*SkillFile, error)
	// ListCatalogSkills ListCatalogSkills lists skills visible to the current user/service consumer.
	ListCatalogSkills(context.Context, *ListCatalogSkillsRequest) (*ListCatalogSkillsResponse, error)
	// ListSkillShares ListSkillShares lists Casdoor/Casbin policy grants created for one Skill.
	ListSkillShares(context.Context, *ListSkillSharesRequest) (*ListSkillSharesResponse, error)
	// ListSkillVersionFiles ListSkillVersionFiles lists files stored for one skill version.
	ListSkillVersionFiles(context.Context, *ListSkillVersionFilesRequest) (*ListSkillVersionFilesResponse, error)
	// ListSkillVersions ListSkillVersions lists versions of one canonical skill.
	ListSkillVersions(context.Context, *ListSkillVersionsRequest) (*ListSkillVersionsResponse, error)
	// ListSkills ListSkills lists canonical skills for management views.
	ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error)
	// OfflineSkillVersion OfflineSkillVersion removes one online version from catalog/runtime use.
	OfflineSkillVersion(context.Context, *SkillVersionActionRequest) (*SkillVersion, error)
	// OnlineSkillVersion OnlineSkillVersion makes one published version consumable by catalog/runtime.
	OnlineSkillVersion(context.Context, *SkillVersionActionRequest) (*SkillVersion, error)
	// PublishSkillVersion PublishSkillVersion marks a submitted version as published.
	PublishSkillVersion(context.Context, *SkillVersionActionRequest) (*SkillVersion, error)
	// SubmitSkillVersion SubmitSkillVersion marks a draft version ready for publish.
	SubmitSkillVersion(context.Context, *SkillVersionActionRequest) (*SkillVersion, error)
	// UpdateSkill UpdateSkill updates mutable fields of one canonical skill.
	UpdateSkill(context.Context, *UpdateSkillRequest) (*Skill, error)
	// UploadSkillPackage UploadSkillPackage imports a zipped Skill package into draft version files.
	UploadSkillPackage(context.Context, *UploadSkillPackageRequest) (*SkillVersion, error)
}

func RegisterSkillServiceHTTPServer(s *http.Server, srv SkillServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v3/aihub/skills", _SkillService_CreateSkill0_HTTP_Handler(srv))
	r.Handle("PUT", "/v3/aihub/skills/{name}", _SkillService_UpdateSkill0_HTTP_Handler(srv))
	r.Handle("GET", "/v3/aihub/skills", _SkillService_ListSkills0_HTTP_Handler(srv))
	r.Handle("GET", "/v3/aihub/skills/{name}", _SkillService_GetSkill0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v3/aihub/skills/{name}", _SkillService_DeleteSkill0_HTTP_Handler(srv))
	r.Handle("POST", "/v3/aihub/skills:upload", _SkillService_UploadSkillPackage0_HTTP_Handler(srv))
	r.Handle("GET", "/v3/aihub/skills/{name}/versions", _SkillService_ListSkillVersions0_HTTP_Handler(srv))
	r.Handle("GET", "/v3/aihub/skills/{name}/versions/{version}", _SkillService_GetSkillVersion0_HTTP_Handler(srv))
	r.Handle("POST", "/v3/aihub/skills/{name}/versions/{version}:submit", _SkillService_SubmitSkillVersion0_HTTP_Handler(srv))
	r.Handle("POST", "/v3/aihub/skills/{name}/versions/{version}:publish", _SkillService_PublishSkillVersion0_HTTP_Handler(srv))
	r.Handle("POST", "/v3/aihub/skills/{name}/versions/{version}:force-publish", _SkillService_ForcePublishSkillVersion0_HTTP_Handler(srv))
	r.Handle("POST", "/v3/aihub/skills/{name}/versions/{version}:online", _SkillService_OnlineSkillVersion0_HTTP_Handler(srv))
	r.Handle("POST", "/v3/aihub/skills/{name}/versions/{version}:offline", _SkillService_OfflineSkillVersion0_HTTP_Handler(srv))
	r.Handle("GET", "/v3/aihub/skills/{name}/versions/{version}/download", _SkillService_DownloadSkillVersion0_HTTP_Handler(srv))
	r.Handle("GET", "/v3/aihub/skills/{name}/versions/{version}/files", _SkillService_ListSkillVersionFiles0_HTTP_Handler(srv))
	r.Handle("GET", "/v3/aihub/skills/{name}/versions/{version}/file", _SkillService_GetSkillVersionFile0_HTTP_Handler(srv))
	r.Handle("GET", "/v3/aihub/skills/{name}/compare", _SkillService_CompareSkillVersions0_HTTP_Handler(srv))
	r.Handle("GET", "/v3/aihub/skills/{name}/shares", _SkillService_ListSkillShares0_HTTP_Handler(srv))
	r.Handle("POST", "/v3/aihub/skills/{name}/shares", _SkillService_CreateSkillShare0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v3/aihub/skills/{name}/shares/{grant_id}", _SkillService_DeleteSkillShare0_HTTP_Handler(srv))
	r.Handle("GET", "/v3/aihub/catalog/skills", _SkillService_ListCatalogSkills0_HTTP_Handler(srv))
	r.Handle("GET", "/v3/aihub/catalog/skills/{name}", _SkillService_GetCatalogSkill0_HTTP_Handler(srv))
	r.Handle("GET", "/v3/aihub/catalog/skills/{name}/manifest", _SkillService_GetCatalogSkillManifest0_HTTP_Handler(srv))
	r.Handle("GET", "/v3/aihub/catalog/skills/{name}/versions/{version}/download", _SkillService_DownloadCatalogSkillVersion0_HTTP_Handler(srv))
}

func _SkillService_CreateSkill0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSkillRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceCreateSkill)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSkill(ctx, req.(*CreateSkillRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Skill)
		return ctx.Result(200, reply)
	}
}

func _SkillService_UpdateSkill0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSkillRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceUpdateSkill)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSkill(ctx, req.(*UpdateSkillRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Skill)
		return ctx.Result(200, reply)
	}
}

func _SkillService_ListSkills0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSkillsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceListSkills)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSkills(ctx, req.(*ListSkillsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSkillsResponse)
		return ctx.Result(200, reply)
	}
}

func _SkillService_GetSkill0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSkillRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceGetSkill)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSkill(ctx, req.(*GetSkillRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Skill)
		return ctx.Result(200, reply)
	}
}

func _SkillService_DeleteSkill0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteSkillRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceDeleteSkill)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSkill(ctx, req.(*DeleteSkillRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _SkillService_UploadSkillPackage0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadSkillPackageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceUploadSkillPackage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadSkillPackage(ctx, req.(*UploadSkillPackageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SkillVersion)
		return ctx.Result(200, reply)
	}
}

func _SkillService_ListSkillVersions0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSkillVersionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceListSkillVersions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSkillVersions(ctx, req.(*ListSkillVersionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSkillVersionsResponse)
		return ctx.Result(200, reply)
	}
}

func _SkillService_GetSkillVersion0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSkillVersionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceGetSkillVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSkillVersion(ctx, req.(*GetSkillVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SkillVersion)
		return ctx.Result(200, reply)
	}
}

func _SkillService_SubmitSkillVersion0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SkillVersionActionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceSubmitSkillVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitSkillVersion(ctx, req.(*SkillVersionActionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SkillVersion)
		return ctx.Result(200, reply)
	}
}

func _SkillService_PublishSkillVersion0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SkillVersionActionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServicePublishSkillVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PublishSkillVersion(ctx, req.(*SkillVersionActionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SkillVersion)
		return ctx.Result(200, reply)
	}
}

func _SkillService_ForcePublishSkillVersion0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SkillVersionActionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceForcePublishSkillVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ForcePublishSkillVersion(ctx, req.(*SkillVersionActionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SkillVersion)
		return ctx.Result(200, reply)
	}
}

func _SkillService_OnlineSkillVersion0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SkillVersionActionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceOnlineSkillVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.OnlineSkillVersion(ctx, req.(*SkillVersionActionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SkillVersion)
		return ctx.Result(200, reply)
	}
}

func _SkillService_OfflineSkillVersion0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SkillVersionActionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceOfflineSkillVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.OfflineSkillVersion(ctx, req.(*SkillVersionActionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SkillVersion)
		return ctx.Result(200, reply)
	}
}

func _SkillService_DownloadSkillVersion0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DownloadSkillVersionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceDownloadSkillVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DownloadSkillVersion(ctx, req.(*DownloadSkillVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SkillPackageDownload)
		return ctx.Result(200, reply)
	}
}

func _SkillService_ListSkillVersionFiles0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSkillVersionFilesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceListSkillVersionFiles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSkillVersionFiles(ctx, req.(*ListSkillVersionFilesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSkillVersionFilesResponse)
		return ctx.Result(200, reply)
	}
}

func _SkillService_GetSkillVersionFile0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSkillVersionFileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceGetSkillVersionFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSkillVersionFile(ctx, req.(*GetSkillVersionFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SkillFile)
		return ctx.Result(200, reply)
	}
}

func _SkillService_CompareSkillVersions0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CompareSkillVersionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceCompareSkillVersions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CompareSkillVersions(ctx, req.(*CompareSkillVersionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CompareSkillVersionsResponse)
		return ctx.Result(200, reply)
	}
}

func _SkillService_ListSkillShares0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSkillSharesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceListSkillShares)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSkillShares(ctx, req.(*ListSkillSharesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSkillSharesResponse)
		return ctx.Result(200, reply)
	}
}

func _SkillService_CreateSkillShare0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSkillShareRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceCreateSkillShare)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSkillShare(ctx, req.(*CreateSkillShareRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SkillShare)
		return ctx.Result(200, reply)
	}
}

func _SkillService_DeleteSkillShare0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteSkillShareRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceDeleteSkillShare)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSkillShare(ctx, req.(*DeleteSkillShareRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _SkillService_ListCatalogSkills0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCatalogSkillsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceListCatalogSkills)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCatalogSkills(ctx, req.(*ListCatalogSkillsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCatalogSkillsResponse)
		return ctx.Result(200, reply)
	}
}

func _SkillService_GetCatalogSkill0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCatalogSkillRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceGetCatalogSkill)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCatalogSkill(ctx, req.(*GetCatalogSkillRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Skill)
		return ctx.Result(200, reply)
	}
}

func _SkillService_GetCatalogSkillManifest0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCatalogSkillManifestRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceGetCatalogSkillManifest)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCatalogSkillManifest(ctx, req.(*GetCatalogSkillManifestRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SkillManifest)
		return ctx.Result(200, reply)
	}
}

func _SkillService_DownloadCatalogSkillVersion0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DownloadSkillVersionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceDownloadCatalogSkillVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DownloadCatalogSkillVersion(ctx, req.(*DownloadSkillVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SkillPackageDownload)
		return ctx.Result(200, reply)
	}
}

type SkillServiceHTTPClient interface {
	// CompareSkillVersions CompareSkillVersions returns SKILL.md and file lists for two versions.
	CompareSkillVersions(ctx context.Context, req *CompareSkillVersionsRequest, opts ...http.CallOption) (rsp *CompareSkillVersionsResponse, err error)
	// CreateSkill CreateSkill creates one canonical skill.
	CreateSkill(ctx context.Context, req *CreateSkillRequest, opts ...http.CallOption) (rsp *Skill, err error)
	// CreateSkillShare CreateSkillShare grants one user/service/app/agent/workflow access to one Skill.
	CreateSkillShare(ctx context.Context, req *CreateSkillShareRequest, opts ...http.CallOption) (rsp *SkillShare, err error)
	// DeleteSkill DeleteSkill soft-deletes one canonical skill by name.
	DeleteSkill(ctx context.Context, req *DeleteSkillRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// DeleteSkillShare DeleteSkillShare revokes all policy actions for one subject on one Skill.
	DeleteSkillShare(ctx context.Context, req *DeleteSkillShareRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// DownloadCatalogSkillVersion DownloadCatalogSkillVersion returns the package for a catalog-consumable version.
	DownloadCatalogSkillVersion(ctx context.Context, req *DownloadSkillVersionRequest, opts ...http.CallOption) (rsp *SkillPackageDownload, err error)
	// DownloadSkillVersion DownloadSkillVersion returns the version package bytes with cache metadata.
	DownloadSkillVersion(ctx context.Context, req *DownloadSkillVersionRequest, opts ...http.CallOption) (rsp *SkillPackageDownload, err error)
	// ForcePublishSkillVersion ForcePublishSkillVersion lets an operator publish without normal submit state.
	ForcePublishSkillVersion(ctx context.Context, req *SkillVersionActionRequest, opts ...http.CallOption) (rsp *SkillVersion, err error)
	// GetCatalogSkill GetCatalogSkill returns one skill for Agent/Runtime/Catalog consumers.
	GetCatalogSkill(ctx context.Context, req *GetCatalogSkillRequest, opts ...http.CallOption) (rsp *Skill, err error)
	// GetCatalogSkillManifest GetCatalogSkillManifest returns the online version manifest for runtime consumers.
	GetCatalogSkillManifest(ctx context.Context, req *GetCatalogSkillManifestRequest, opts ...http.CallOption) (rsp *SkillManifest, err error)
	// GetSkill GetSkill returns one canonical skill by name for management views.
	GetSkill(ctx context.Context, req *GetSkillRequest, opts ...http.CallOption) (rsp *Skill, err error)
	// GetSkillVersion GetSkillVersion returns one version metadata record.
	GetSkillVersion(ctx context.Context, req *GetSkillVersionRequest, opts ...http.CallOption) (rsp *SkillVersion, err error)
	// GetSkillVersionFile GetSkillVersionFile returns one text or base64-encoded file content.
	GetSkillVersionFile(ctx context.Context, req *GetSkillVersionFileRequest, opts ...http.CallOption) (rsp *SkillFile, err error)
	// ListCatalogSkills ListCatalogSkills lists skills visible to the current user/service consumer.
	ListCatalogSkills(ctx context.Context, req *ListCatalogSkillsRequest, opts ...http.CallOption) (rsp *ListCatalogSkillsResponse, err error)
	// ListSkillShares ListSkillShares lists Casdoor/Casbin policy grants created for one Skill.
	ListSkillShares(ctx context.Context, req *ListSkillSharesRequest, opts ...http.CallOption) (rsp *ListSkillSharesResponse, err error)
	// ListSkillVersionFiles ListSkillVersionFiles lists files stored for one skill version.
	ListSkillVersionFiles(ctx context.Context, req *ListSkillVersionFilesRequest, opts ...http.CallOption) (rsp *ListSkillVersionFilesResponse, err error)
	// ListSkillVersions ListSkillVersions lists versions of one canonical skill.
	ListSkillVersions(ctx context.Context, req *ListSkillVersionsRequest, opts ...http.CallOption) (rsp *ListSkillVersionsResponse, err error)
	// ListSkills ListSkills lists canonical skills for management views.
	ListSkills(ctx context.Context, req *ListSkillsRequest, opts ...http.CallOption) (rsp *ListSkillsResponse, err error)
	// OfflineSkillVersion OfflineSkillVersion removes one online version from catalog/runtime use.
	OfflineSkillVersion(ctx context.Context, req *SkillVersionActionRequest, opts ...http.CallOption) (rsp *SkillVersion, err error)
	// OnlineSkillVersion OnlineSkillVersion makes one published version consumable by catalog/runtime.
	OnlineSkillVersion(ctx context.Context, req *SkillVersionActionRequest, opts ...http.CallOption) (rsp *SkillVersion, err error)
	// PublishSkillVersion PublishSkillVersion marks a submitted version as published.
	PublishSkillVersion(ctx context.Context, req *SkillVersionActionRequest, opts ...http.CallOption) (rsp *SkillVersion, err error)
	// SubmitSkillVersion SubmitSkillVersion marks a draft version ready for publish.
	SubmitSkillVersion(ctx context.Context, req *SkillVersionActionRequest, opts ...http.CallOption) (rsp *SkillVersion, err error)
	// UpdateSkill UpdateSkill updates mutable fields of one canonical skill.
	UpdateSkill(ctx context.Context, req *UpdateSkillRequest, opts ...http.CallOption) (rsp *Skill, err error)
	// UploadSkillPackage UploadSkillPackage imports a zipped Skill package into draft version files.
	UploadSkillPackage(ctx context.Context, req *UploadSkillPackageRequest, opts ...http.CallOption) (rsp *SkillVersion, err error)
}

type SkillServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSkillServiceHTTPClient(client *http.Client) SkillServiceHTTPClient {
	return &SkillServiceHTTPClientImpl{client}
}

// CompareSkillVersions CompareSkillVersions returns SKILL.md and file lists for two versions.
func (c *SkillServiceHTTPClientImpl) CompareSkillVersions(ctx context.Context, in *CompareSkillVersionsRequest, opts ...http.CallOption) (*CompareSkillVersionsResponse, error) {
	var out CompareSkillVersionsResponse
	pattern := "/v3/aihub/skills/{name}/compare"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceCompareSkillVersions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateSkill CreateSkill creates one canonical skill.
func (c *SkillServiceHTTPClientImpl) CreateSkill(ctx context.Context, in *CreateSkillRequest, opts ...http.CallOption) (*Skill, error) {
	var out Skill
	pattern := "/v3/aihub/skills"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSkillServiceCreateSkill),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateSkillShare CreateSkillShare grants one user/service/app/agent/workflow access to one Skill.
func (c *SkillServiceHTTPClientImpl) CreateSkillShare(ctx context.Context, in *CreateSkillShareRequest, opts ...http.CallOption) (*SkillShare, error) {
	var out SkillShare
	pattern := "/v3/aihub/skills/{name}/shares"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSkillServiceCreateSkillShare),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteSkill DeleteSkill soft-deletes one canonical skill by name.
func (c *SkillServiceHTTPClientImpl) DeleteSkill(ctx context.Context, in *DeleteSkillRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v3/aihub/skills/{name}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceDeleteSkill),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteSkillShare DeleteSkillShare revokes all policy actions for one subject on one Skill.
func (c *SkillServiceHTTPClientImpl) DeleteSkillShare(ctx context.Context, in *DeleteSkillShareRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v3/aihub/skills/{name}/shares/{grant_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceDeleteSkillShare),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DownloadCatalogSkillVersion DownloadCatalogSkillVersion returns the package for a catalog-consumable version.
func (c *SkillServiceHTTPClientImpl) DownloadCatalogSkillVersion(ctx context.Context, in *DownloadSkillVersionRequest, opts ...http.CallOption) (*SkillPackageDownload, error) {
	var out SkillPackageDownload
	pattern := "/v3/aihub/catalog/skills/{name}/versions/{version}/download"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceDownloadCatalogSkillVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DownloadSkillVersion DownloadSkillVersion returns the version package bytes with cache metadata.
func (c *SkillServiceHTTPClientImpl) DownloadSkillVersion(ctx context.Context, in *DownloadSkillVersionRequest, opts ...http.CallOption) (*SkillPackageDownload, error) {
	var out SkillPackageDownload
	pattern := "/v3/aihub/skills/{name}/versions/{version}/download"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceDownloadSkillVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ForcePublishSkillVersion ForcePublishSkillVersion lets an operator publish without normal submit state.
func (c *SkillServiceHTTPClientImpl) ForcePublishSkillVersion(ctx context.Context, in *SkillVersionActionRequest, opts ...http.CallOption) (*SkillVersion, error) {
	var out SkillVersion
	pattern := "/v3/aihub/skills/{name}/versions/{version}:force-publish"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSkillServiceForcePublishSkillVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCatalogSkill GetCatalogSkill returns one skill for Agent/Runtime/Catalog consumers.
func (c *SkillServiceHTTPClientImpl) GetCatalogSkill(ctx context.Context, in *GetCatalogSkillRequest, opts ...http.CallOption) (*Skill, error) {
	var out Skill
	pattern := "/v3/aihub/catalog/skills/{name}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceGetCatalogSkill),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCatalogSkillManifest GetCatalogSkillManifest returns the online version manifest for runtime consumers.
func (c *SkillServiceHTTPClientImpl) GetCatalogSkillManifest(ctx context.Context, in *GetCatalogSkillManifestRequest, opts ...http.CallOption) (*SkillManifest, error) {
	var out SkillManifest
	pattern := "/v3/aihub/catalog/skills/{name}/manifest"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceGetCatalogSkillManifest),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSkill GetSkill returns one canonical skill by name for management views.
func (c *SkillServiceHTTPClientImpl) GetSkill(ctx context.Context, in *GetSkillRequest, opts ...http.CallOption) (*Skill, error) {
	var out Skill
	pattern := "/v3/aihub/skills/{name}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceGetSkill),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSkillVersion GetSkillVersion returns one version metadata record.
func (c *SkillServiceHTTPClientImpl) GetSkillVersion(ctx context.Context, in *GetSkillVersionRequest, opts ...http.CallOption) (*SkillVersion, error) {
	var out SkillVersion
	pattern := "/v3/aihub/skills/{name}/versions/{version}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceGetSkillVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSkillVersionFile GetSkillVersionFile returns one text or base64-encoded file content.
func (c *SkillServiceHTTPClientImpl) GetSkillVersionFile(ctx context.Context, in *GetSkillVersionFileRequest, opts ...http.CallOption) (*SkillFile, error) {
	var out SkillFile
	pattern := "/v3/aihub/skills/{name}/versions/{version}/file"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceGetSkillVersionFile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCatalogSkills ListCatalogSkills lists skills visible to the current user/service consumer.
func (c *SkillServiceHTTPClientImpl) ListCatalogSkills(ctx context.Context, in *ListCatalogSkillsRequest, opts ...http.CallOption) (*ListCatalogSkillsResponse, error) {
	var out ListCatalogSkillsResponse
	pattern := "/v3/aihub/catalog/skills"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceListCatalogSkills),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSkillShares ListSkillShares lists Casdoor/Casbin policy grants created for one Skill.
func (c *SkillServiceHTTPClientImpl) ListSkillShares(ctx context.Context, in *ListSkillSharesRequest, opts ...http.CallOption) (*ListSkillSharesResponse, error) {
	var out ListSkillSharesResponse
	pattern := "/v3/aihub/skills/{name}/shares"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceListSkillShares),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSkillVersionFiles ListSkillVersionFiles lists files stored for one skill version.
func (c *SkillServiceHTTPClientImpl) ListSkillVersionFiles(ctx context.Context, in *ListSkillVersionFilesRequest, opts ...http.CallOption) (*ListSkillVersionFilesResponse, error) {
	var out ListSkillVersionFilesResponse
	pattern := "/v3/aihub/skills/{name}/versions/{version}/files"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceListSkillVersionFiles),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSkillVersions ListSkillVersions lists versions of one canonical skill.
func (c *SkillServiceHTTPClientImpl) ListSkillVersions(ctx context.Context, in *ListSkillVersionsRequest, opts ...http.CallOption) (*ListSkillVersionsResponse, error) {
	var out ListSkillVersionsResponse
	pattern := "/v3/aihub/skills/{name}/versions"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceListSkillVersions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSkills ListSkills lists canonical skills for management views.
func (c *SkillServiceHTTPClientImpl) ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...http.CallOption) (*ListSkillsResponse, error) {
	var out ListSkillsResponse
	pattern := "/v3/aihub/skills"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSkillServiceListSkills),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// OfflineSkillVersion OfflineSkillVersion removes one online version from catalog/runtime use.
func (c *SkillServiceHTTPClientImpl) OfflineSkillVersion(ctx context.Context, in *SkillVersionActionRequest, opts ...http.CallOption) (*SkillVersion, error) {
	var out SkillVersion
	pattern := "/v3/aihub/skills/{name}/versions/{version}:offline"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSkillServiceOfflineSkillVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// OnlineSkillVersion OnlineSkillVersion makes one published version consumable by catalog/runtime.
func (c *SkillServiceHTTPClientImpl) OnlineSkillVersion(ctx context.Context, in *SkillVersionActionRequest, opts ...http.CallOption) (*SkillVersion, error) {
	var out SkillVersion
	pattern := "/v3/aihub/skills/{name}/versions/{version}:online"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSkillServiceOnlineSkillVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PublishSkillVersion PublishSkillVersion marks a submitted version as published.
func (c *SkillServiceHTTPClientImpl) PublishSkillVersion(ctx context.Context, in *SkillVersionActionRequest, opts ...http.CallOption) (*SkillVersion, error) {
	var out SkillVersion
	pattern := "/v3/aihub/skills/{name}/versions/{version}:publish"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSkillServicePublishSkillVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubmitSkillVersion SubmitSkillVersion marks a draft version ready for publish.
func (c *SkillServiceHTTPClientImpl) SubmitSkillVersion(ctx context.Context, in *SkillVersionActionRequest, opts ...http.CallOption) (*SkillVersion, error) {
	var out SkillVersion
	pattern := "/v3/aihub/skills/{name}/versions/{version}:submit"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSkillServiceSubmitSkillVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateSkill UpdateSkill updates mutable fields of one canonical skill.
func (c *SkillServiceHTTPClientImpl) UpdateSkill(ctx context.Context, in *UpdateSkillRequest, opts ...http.CallOption) (*Skill, error) {
	var out Skill
	pattern := "/v3/aihub/skills/{name}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSkillServiceUpdateSkill),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UploadSkillPackage UploadSkillPackage imports a zipped Skill package into draft version files.
func (c *SkillServiceHTTPClientImpl) UploadSkillPackage(ctx context.Context, in *UploadSkillPackageRequest, opts ...http.CallOption) (*SkillVersion, error) {
	var out SkillVersion
	pattern := "/v3/aihub/skills:upload"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSkillServiceUploadSkillPackage),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
