// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: skill/v1/skill.proto

package skillv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SkillService_CreateSkill_FullMethodName                 = "/api.skill.v1.SkillService/CreateSkill"
	SkillService_UpdateSkill_FullMethodName                 = "/api.skill.v1.SkillService/UpdateSkill"
	SkillService_ListSkills_FullMethodName                  = "/api.skill.v1.SkillService/ListSkills"
	SkillService_GetSkill_FullMethodName                    = "/api.skill.v1.SkillService/GetSkill"
	SkillService_DeleteSkill_FullMethodName                 = "/api.skill.v1.SkillService/DeleteSkill"
	SkillService_UploadSkillPackage_FullMethodName          = "/api.skill.v1.SkillService/UploadSkillPackage"
	SkillService_ListSkillVersions_FullMethodName           = "/api.skill.v1.SkillService/ListSkillVersions"
	SkillService_GetSkillVersion_FullMethodName             = "/api.skill.v1.SkillService/GetSkillVersion"
	SkillService_SubmitSkillVersion_FullMethodName          = "/api.skill.v1.SkillService/SubmitSkillVersion"
	SkillService_PublishSkillVersion_FullMethodName         = "/api.skill.v1.SkillService/PublishSkillVersion"
	SkillService_ForcePublishSkillVersion_FullMethodName    = "/api.skill.v1.SkillService/ForcePublishSkillVersion"
	SkillService_OnlineSkillVersion_FullMethodName          = "/api.skill.v1.SkillService/OnlineSkillVersion"
	SkillService_OfflineSkillVersion_FullMethodName         = "/api.skill.v1.SkillService/OfflineSkillVersion"
	SkillService_DownloadSkillVersion_FullMethodName        = "/api.skill.v1.SkillService/DownloadSkillVersion"
	SkillService_ListSkillVersionFiles_FullMethodName       = "/api.skill.v1.SkillService/ListSkillVersionFiles"
	SkillService_GetSkillVersionFile_FullMethodName         = "/api.skill.v1.SkillService/GetSkillVersionFile"
	SkillService_CompareSkillVersions_FullMethodName        = "/api.skill.v1.SkillService/CompareSkillVersions"
	SkillService_ListSkillShares_FullMethodName             = "/api.skill.v1.SkillService/ListSkillShares"
	SkillService_CreateSkillShare_FullMethodName            = "/api.skill.v1.SkillService/CreateSkillShare"
	SkillService_DeleteSkillShare_FullMethodName            = "/api.skill.v1.SkillService/DeleteSkillShare"
	SkillService_ListCatalogSkills_FullMethodName           = "/api.skill.v1.SkillService/ListCatalogSkills"
	SkillService_GetCatalogSkill_FullMethodName             = "/api.skill.v1.SkillService/GetCatalogSkill"
	SkillService_GetCatalogSkillManifest_FullMethodName     = "/api.skill.v1.SkillService/GetCatalogSkillManifest"
	SkillService_DownloadCatalogSkillVersion_FullMethodName = "/api.skill.v1.SkillService/DownloadCatalogSkillVersion"
)

// SkillServiceClient is the client API for SkillService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SkillService exposes the canonical AIHub Skill API.
//
// This service is the first real business module migrated from the legacy
// backend into the new kratos+kit Hub. It intentionally uses canonical,
// namespace-free resources and a structured PostgreSQL table.
type SkillServiceClient interface {
	// CreateSkill creates one canonical skill.
	CreateSkill(ctx context.Context, in *CreateSkillRequest, opts ...grpc.CallOption) (*Skill, error)
	// UpdateSkill updates mutable fields of one canonical skill.
	UpdateSkill(ctx context.Context, in *UpdateSkillRequest, opts ...grpc.CallOption) (*Skill, error)
	// ListSkills lists canonical skills for management views.
	ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsResponse, error)
	// GetSkill returns one canonical skill by name for management views.
	GetSkill(ctx context.Context, in *GetSkillRequest, opts ...grpc.CallOption) (*Skill, error)
	// DeleteSkill soft-deletes one canonical skill by name.
	DeleteSkill(ctx context.Context, in *DeleteSkillRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// UploadSkillPackage imports a zipped Skill package into draft version files.
	UploadSkillPackage(ctx context.Context, in *UploadSkillPackageRequest, opts ...grpc.CallOption) (*SkillVersion, error)
	// ListSkillVersions lists versions of one canonical skill.
	ListSkillVersions(ctx context.Context, in *ListSkillVersionsRequest, opts ...grpc.CallOption) (*ListSkillVersionsResponse, error)
	// GetSkillVersion returns one version metadata record.
	GetSkillVersion(ctx context.Context, in *GetSkillVersionRequest, opts ...grpc.CallOption) (*SkillVersion, error)
	// SubmitSkillVersion marks a draft version ready for publish.
	SubmitSkillVersion(ctx context.Context, in *SkillVersionActionRequest, opts ...grpc.CallOption) (*SkillVersion, error)
	// PublishSkillVersion marks a submitted version as published.
	PublishSkillVersion(ctx context.Context, in *SkillVersionActionRequest, opts ...grpc.CallOption) (*SkillVersion, error)
	// ForcePublishSkillVersion lets an operator publish without normal submit state.
	ForcePublishSkillVersion(ctx context.Context, in *SkillVersionActionRequest, opts ...grpc.CallOption) (*SkillVersion, error)
	// OnlineSkillVersion makes one published version consumable by catalog/runtime.
	OnlineSkillVersion(ctx context.Context, in *SkillVersionActionRequest, opts ...grpc.CallOption) (*SkillVersion, error)
	// OfflineSkillVersion removes one online version from catalog/runtime use.
	OfflineSkillVersion(ctx context.Context, in *SkillVersionActionRequest, opts ...grpc.CallOption) (*SkillVersion, error)
	// DownloadSkillVersion returns the version package bytes with cache metadata.
	DownloadSkillVersion(ctx context.Context, in *DownloadSkillVersionRequest, opts ...grpc.CallOption) (*SkillPackageDownload, error)
	// ListSkillVersionFiles lists files stored for one skill version.
	ListSkillVersionFiles(ctx context.Context, in *ListSkillVersionFilesRequest, opts ...grpc.CallOption) (*ListSkillVersionFilesResponse, error)
	// GetSkillVersionFile returns one text or base64-encoded file content.
	GetSkillVersionFile(ctx context.Context, in *GetSkillVersionFileRequest, opts ...grpc.CallOption) (*SkillFile, error)
	// CompareSkillVersions returns SKILL.md and file lists for two versions.
	CompareSkillVersions(ctx context.Context, in *CompareSkillVersionsRequest, opts ...grpc.CallOption) (*CompareSkillVersionsResponse, error)
	// ListSkillShares lists Casdoor/Casbin policy grants created for one Skill.
	ListSkillShares(ctx context.Context, in *ListSkillSharesRequest, opts ...grpc.CallOption) (*ListSkillSharesResponse, error)
	// CreateSkillShare grants one user/service/app/agent/workflow access to one Skill.
	CreateSkillShare(ctx context.Context, in *CreateSkillShareRequest, opts ...grpc.CallOption) (*SkillShare, error)
	// DeleteSkillShare revokes all policy actions for one subject on one Skill.
	DeleteSkillShare(ctx context.Context, in *DeleteSkillShareRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListCatalogSkills lists skills visible to the current user/service consumer.
	ListCatalogSkills(ctx context.Context, in *ListCatalogSkillsRequest, opts ...grpc.CallOption) (*ListCatalogSkillsResponse, error)
	// GetCatalogSkill returns one skill for Agent/Runtime/Catalog consumers.
	GetCatalogSkill(ctx context.Context, in *GetCatalogSkillRequest, opts ...grpc.CallOption) (*Skill, error)
	// GetCatalogSkillManifest returns the online version manifest for runtime consumers.
	GetCatalogSkillManifest(ctx context.Context, in *GetCatalogSkillManifestRequest, opts ...grpc.CallOption) (*SkillManifest, error)
	// DownloadCatalogSkillVersion returns the package for a catalog-consumable version.
	DownloadCatalogSkillVersion(ctx context.Context, in *DownloadSkillVersionRequest, opts ...grpc.CallOption) (*SkillPackageDownload, error)
}

type skillServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkillServiceClient(cc grpc.ClientConnInterface) SkillServiceClient {
	return &skillServiceClient{cc}
}

func (c *skillServiceClient) CreateSkill(ctx context.Context, in *CreateSkillRequest, opts ...grpc.CallOption) (*Skill, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Skill)
	err := c.cc.Invoke(ctx, SkillService_CreateSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) UpdateSkill(ctx context.Context, in *UpdateSkillRequest, opts ...grpc.CallOption) (*Skill, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Skill)
	err := c.cc.Invoke(ctx, SkillService_UpdateSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkillsResponse)
	err := c.cc.Invoke(ctx, SkillService_ListSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) GetSkill(ctx context.Context, in *GetSkillRequest, opts ...grpc.CallOption) (*Skill, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Skill)
	err := c.cc.Invoke(ctx, SkillService_GetSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) DeleteSkill(ctx context.Context, in *DeleteSkillRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SkillService_DeleteSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) UploadSkillPackage(ctx context.Context, in *UploadSkillPackageRequest, opts ...grpc.CallOption) (*SkillVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillVersion)
	err := c.cc.Invoke(ctx, SkillService_UploadSkillPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) ListSkillVersions(ctx context.Context, in *ListSkillVersionsRequest, opts ...grpc.CallOption) (*ListSkillVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkillVersionsResponse)
	err := c.cc.Invoke(ctx, SkillService_ListSkillVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) GetSkillVersion(ctx context.Context, in *GetSkillVersionRequest, opts ...grpc.CallOption) (*SkillVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillVersion)
	err := c.cc.Invoke(ctx, SkillService_GetSkillVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) SubmitSkillVersion(ctx context.Context, in *SkillVersionActionRequest, opts ...grpc.CallOption) (*SkillVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillVersion)
	err := c.cc.Invoke(ctx, SkillService_SubmitSkillVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) PublishSkillVersion(ctx context.Context, in *SkillVersionActionRequest, opts ...grpc.CallOption) (*SkillVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillVersion)
	err := c.cc.Invoke(ctx, SkillService_PublishSkillVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) ForcePublishSkillVersion(ctx context.Context, in *SkillVersionActionRequest, opts ...grpc.CallOption) (*SkillVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillVersion)
	err := c.cc.Invoke(ctx, SkillService_ForcePublishSkillVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) OnlineSkillVersion(ctx context.Context, in *SkillVersionActionRequest, opts ...grpc.CallOption) (*SkillVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillVersion)
	err := c.cc.Invoke(ctx, SkillService_OnlineSkillVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) OfflineSkillVersion(ctx context.Context, in *SkillVersionActionRequest, opts ...grpc.CallOption) (*SkillVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillVersion)
	err := c.cc.Invoke(ctx, SkillService_OfflineSkillVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) DownloadSkillVersion(ctx context.Context, in *DownloadSkillVersionRequest, opts ...grpc.CallOption) (*SkillPackageDownload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillPackageDownload)
	err := c.cc.Invoke(ctx, SkillService_DownloadSkillVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) ListSkillVersionFiles(ctx context.Context, in *ListSkillVersionFilesRequest, opts ...grpc.CallOption) (*ListSkillVersionFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkillVersionFilesResponse)
	err := c.cc.Invoke(ctx, SkillService_ListSkillVersionFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) GetSkillVersionFile(ctx context.Context, in *GetSkillVersionFileRequest, opts ...grpc.CallOption) (*SkillFile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillFile)
	err := c.cc.Invoke(ctx, SkillService_GetSkillVersionFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) CompareSkillVersions(ctx context.Context, in *CompareSkillVersionsRequest, opts ...grpc.CallOption) (*CompareSkillVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareSkillVersionsResponse)
	err := c.cc.Invoke(ctx, SkillService_CompareSkillVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) ListSkillShares(ctx context.Context, in *ListSkillSharesRequest, opts ...grpc.CallOption) (*ListSkillSharesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkillSharesResponse)
	err := c.cc.Invoke(ctx, SkillService_ListSkillShares_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) CreateSkillShare(ctx context.Context, in *CreateSkillShareRequest, opts ...grpc.CallOption) (*SkillShare, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillShare)
	err := c.cc.Invoke(ctx, SkillService_CreateSkillShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) DeleteSkillShare(ctx context.Context, in *DeleteSkillShareRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SkillService_DeleteSkillShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) ListCatalogSkills(ctx context.Context, in *ListCatalogSkillsRequest, opts ...grpc.CallOption) (*ListCatalogSkillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCatalogSkillsResponse)
	err := c.cc.Invoke(ctx, SkillService_ListCatalogSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) GetCatalogSkill(ctx context.Context, in *GetCatalogSkillRequest, opts ...grpc.CallOption) (*Skill, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Skill)
	err := c.cc.Invoke(ctx, SkillService_GetCatalogSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) GetCatalogSkillManifest(ctx context.Context, in *GetCatalogSkillManifestRequest, opts ...grpc.CallOption) (*SkillManifest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillManifest)
	err := c.cc.Invoke(ctx, SkillService_GetCatalogSkillManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) DownloadCatalogSkillVersion(ctx context.Context, in *DownloadSkillVersionRequest, opts ...grpc.CallOption) (*SkillPackageDownload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillPackageDownload)
	err := c.cc.Invoke(ctx, SkillService_DownloadCatalogSkillVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkillServiceServer is the server API for SkillService service.
// All implementations must embed UnimplementedSkillServiceServer
// for forward compatibility.
//
// SkillService exposes the canonical AIHub Skill API.
//
// This service is the first real business module migrated from the legacy
// backend into the new kratos+kit Hub. It intentionally uses canonical,
// namespace-free resources and a structured PostgreSQL table.
type SkillServiceServer interface {
	// CreateSkill creates one canonical skill.
	CreateSkill(context.Context, *CreateSkillRequest) (*Skill, error)
	// UpdateSkill updates mutable fields of one canonical skill.
	UpdateSkill(context.Context, *UpdateSkillRequest) (*Skill, error)
	// ListSkills lists canonical skills for management views.
	ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error)
	// GetSkill returns one canonical skill by name for management views.
	GetSkill(context.Context, *GetSkillRequest) (*Skill, error)
	// DeleteSkill soft-deletes one canonical skill by name.
	DeleteSkill(context.Context, *DeleteSkillRequest) (*emptypb.Empty, error)
	// UploadSkillPackage imports a zipped Skill package into draft version files.
	UploadSkillPackage(context.Context, *UploadSkillPackageRequest) (*SkillVersion, error)
	// ListSkillVersions lists versions of one canonical skill.
	ListSkillVersions(context.Context, *ListSkillVersionsRequest) (*ListSkillVersionsResponse, error)
	// GetSkillVersion returns one version metadata record.
	GetSkillVersion(context.Context, *GetSkillVersionRequest) (*SkillVersion, error)
	// SubmitSkillVersion marks a draft version ready for publish.
	SubmitSkillVersion(context.Context, *SkillVersionActionRequest) (*SkillVersion, error)
	// PublishSkillVersion marks a submitted version as published.
	PublishSkillVersion(context.Context, *SkillVersionActionRequest) (*SkillVersion, error)
	// ForcePublishSkillVersion lets an operator publish without normal submit state.
	ForcePublishSkillVersion(context.Context, *SkillVersionActionRequest) (*SkillVersion, error)
	// OnlineSkillVersion makes one published version consumable by catalog/runtime.
	OnlineSkillVersion(context.Context, *SkillVersionActionRequest) (*SkillVersion, error)
	// OfflineSkillVersion removes one online version from catalog/runtime use.
	OfflineSkillVersion(context.Context, *SkillVersionActionRequest) (*SkillVersion, error)
	// DownloadSkillVersion returns the version package bytes with cache metadata.
	DownloadSkillVersion(context.Context, *DownloadSkillVersionRequest) (*SkillPackageDownload, error)
	// ListSkillVersionFiles lists files stored for one skill version.
	ListSkillVersionFiles(context.Context, *ListSkillVersionFilesRequest) (*ListSkillVersionFilesResponse, error)
	// GetSkillVersionFile returns one text or base64-encoded file content.
	GetSkillVersionFile(context.Context, *GetSkillVersionFileRequest) (*SkillFile, error)
	// CompareSkillVersions returns SKILL.md and file lists for two versions.
	CompareSkillVersions(context.Context, *CompareSkillVersionsRequest) (*CompareSkillVersionsResponse, error)
	// ListSkillShares lists Casdoor/Casbin policy grants created for one Skill.
	ListSkillShares(context.Context, *ListSkillSharesRequest) (*ListSkillSharesResponse, error)
	// CreateSkillShare grants one user/service/app/agent/workflow access to one Skill.
	CreateSkillShare(context.Context, *CreateSkillShareRequest) (*SkillShare, error)
	// DeleteSkillShare revokes all policy actions for one subject on one Skill.
	DeleteSkillShare(context.Context, *DeleteSkillShareRequest) (*emptypb.Empty, error)
	// ListCatalogSkills lists skills visible to the current user/service consumer.
	ListCatalogSkills(context.Context, *ListCatalogSkillsRequest) (*ListCatalogSkillsResponse, error)
	// GetCatalogSkill returns one skill for Agent/Runtime/Catalog consumers.
	GetCatalogSkill(context.Context, *GetCatalogSkillRequest) (*Skill, error)
	// GetCatalogSkillManifest returns the online version manifest for runtime consumers.
	GetCatalogSkillManifest(context.Context, *GetCatalogSkillManifestRequest) (*SkillManifest, error)
	// DownloadCatalogSkillVersion returns the package for a catalog-consumable version.
	DownloadCatalogSkillVersion(context.Context, *DownloadSkillVersionRequest) (*SkillPackageDownload, error)
	mustEmbedUnimplementedSkillServiceServer()
}

// UnimplementedSkillServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSkillServiceServer struct{}

func (UnimplementedSkillServiceServer) CreateSkill(context.Context, *CreateSkillRequest) (*Skill, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSkill not implemented")
}
func (UnimplementedSkillServiceServer) UpdateSkill(context.Context, *UpdateSkillRequest) (*Skill, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSkill not implemented")
}
func (UnimplementedSkillServiceServer) ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSkills not implemented")
}
func (UnimplementedSkillServiceServer) GetSkill(context.Context, *GetSkillRequest) (*Skill, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSkill not implemented")
}
func (UnimplementedSkillServiceServer) DeleteSkill(context.Context, *DeleteSkillRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSkill not implemented")
}
func (UnimplementedSkillServiceServer) UploadSkillPackage(context.Context, *UploadSkillPackageRequest) (*SkillVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadSkillPackage not implemented")
}
func (UnimplementedSkillServiceServer) ListSkillVersions(context.Context, *ListSkillVersionsRequest) (*ListSkillVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSkillVersions not implemented")
}
func (UnimplementedSkillServiceServer) GetSkillVersion(context.Context, *GetSkillVersionRequest) (*SkillVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSkillVersion not implemented")
}
func (UnimplementedSkillServiceServer) SubmitSkillVersion(context.Context, *SkillVersionActionRequest) (*SkillVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitSkillVersion not implemented")
}
func (UnimplementedSkillServiceServer) PublishSkillVersion(context.Context, *SkillVersionActionRequest) (*SkillVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishSkillVersion not implemented")
}
func (UnimplementedSkillServiceServer) ForcePublishSkillVersion(context.Context, *SkillVersionActionRequest) (*SkillVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method ForcePublishSkillVersion not implemented")
}
func (UnimplementedSkillServiceServer) OnlineSkillVersion(context.Context, *SkillVersionActionRequest) (*SkillVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method OnlineSkillVersion not implemented")
}
func (UnimplementedSkillServiceServer) OfflineSkillVersion(context.Context, *SkillVersionActionRequest) (*SkillVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method OfflineSkillVersion not implemented")
}
func (UnimplementedSkillServiceServer) DownloadSkillVersion(context.Context, *DownloadSkillVersionRequest) (*SkillPackageDownload, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadSkillVersion not implemented")
}
func (UnimplementedSkillServiceServer) ListSkillVersionFiles(context.Context, *ListSkillVersionFilesRequest) (*ListSkillVersionFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSkillVersionFiles not implemented")
}
func (UnimplementedSkillServiceServer) GetSkillVersionFile(context.Context, *GetSkillVersionFileRequest) (*SkillFile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSkillVersionFile not implemented")
}
func (UnimplementedSkillServiceServer) CompareSkillVersions(context.Context, *CompareSkillVersionsRequest) (*CompareSkillVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompareSkillVersions not implemented")
}
func (UnimplementedSkillServiceServer) ListSkillShares(context.Context, *ListSkillSharesRequest) (*ListSkillSharesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSkillShares not implemented")
}
func (UnimplementedSkillServiceServer) CreateSkillShare(context.Context, *CreateSkillShareRequest) (*SkillShare, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSkillShare not implemented")
}
func (UnimplementedSkillServiceServer) DeleteSkillShare(context.Context, *DeleteSkillShareRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSkillShare not implemented")
}
func (UnimplementedSkillServiceServer) ListCatalogSkills(context.Context, *ListCatalogSkillsRequest) (*ListCatalogSkillsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCatalogSkills not implemented")
}
func (UnimplementedSkillServiceServer) GetCatalogSkill(context.Context, *GetCatalogSkillRequest) (*Skill, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCatalogSkill not implemented")
}
func (UnimplementedSkillServiceServer) GetCatalogSkillManifest(context.Context, *GetCatalogSkillManifestRequest) (*SkillManifest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCatalogSkillManifest not implemented")
}
func (UnimplementedSkillServiceServer) DownloadCatalogSkillVersion(context.Context, *DownloadSkillVersionRequest) (*SkillPackageDownload, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadCatalogSkillVersion not implemented")
}
func (UnimplementedSkillServiceServer) mustEmbedUnimplementedSkillServiceServer() {}
func (UnimplementedSkillServiceServer) testEmbeddedByValue()                      {}

// UnsafeSkillServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkillServiceServer will
// result in compilation errors.
type UnsafeSkillServiceServer interface {
	mustEmbedUnimplementedSkillServiceServer()
}

func RegisterSkillServiceServer(s grpc.ServiceRegistrar, srv SkillServiceServer) {
	// If the following call panics, it indicates UnimplementedSkillServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SkillService_ServiceDesc, srv)
}

func _SkillService_CreateSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).CreateSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_CreateSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).CreateSkill(ctx, req.(*CreateSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_UpdateSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).UpdateSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_UpdateSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).UpdateSkill(ctx, req.(*UpdateSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_ListSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).ListSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_ListSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).ListSkills(ctx, req.(*ListSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_GetSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).GetSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_GetSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).GetSkill(ctx, req.(*GetSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_DeleteSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).DeleteSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_DeleteSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).DeleteSkill(ctx, req.(*DeleteSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_UploadSkillPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadSkillPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).UploadSkillPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_UploadSkillPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).UploadSkillPackage(ctx, req.(*UploadSkillPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_ListSkillVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).ListSkillVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_ListSkillVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).ListSkillVersions(ctx, req.(*ListSkillVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_GetSkillVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkillVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).GetSkillVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_GetSkillVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).GetSkillVersion(ctx, req.(*GetSkillVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_SubmitSkillVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillVersionActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).SubmitSkillVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_SubmitSkillVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).SubmitSkillVersion(ctx, req.(*SkillVersionActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_PublishSkillVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillVersionActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).PublishSkillVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_PublishSkillVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).PublishSkillVersion(ctx, req.(*SkillVersionActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_ForcePublishSkillVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillVersionActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).ForcePublishSkillVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_ForcePublishSkillVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).ForcePublishSkillVersion(ctx, req.(*SkillVersionActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_OnlineSkillVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillVersionActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).OnlineSkillVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_OnlineSkillVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).OnlineSkillVersion(ctx, req.(*SkillVersionActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_OfflineSkillVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillVersionActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).OfflineSkillVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_OfflineSkillVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).OfflineSkillVersion(ctx, req.(*SkillVersionActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_DownloadSkillVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadSkillVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).DownloadSkillVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_DownloadSkillVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).DownloadSkillVersion(ctx, req.(*DownloadSkillVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_ListSkillVersionFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillVersionFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).ListSkillVersionFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_ListSkillVersionFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).ListSkillVersionFiles(ctx, req.(*ListSkillVersionFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_GetSkillVersionFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkillVersionFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).GetSkillVersionFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_GetSkillVersionFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).GetSkillVersionFile(ctx, req.(*GetSkillVersionFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_CompareSkillVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareSkillVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).CompareSkillVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_CompareSkillVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).CompareSkillVersions(ctx, req.(*CompareSkillVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_ListSkillShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillSharesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).ListSkillShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_ListSkillShares_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).ListSkillShares(ctx, req.(*ListSkillSharesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_CreateSkillShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSkillShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).CreateSkillShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_CreateSkillShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).CreateSkillShare(ctx, req.(*CreateSkillShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_DeleteSkillShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSkillShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).DeleteSkillShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_DeleteSkillShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).DeleteSkillShare(ctx, req.(*DeleteSkillShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_ListCatalogSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCatalogSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).ListCatalogSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_ListCatalogSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).ListCatalogSkills(ctx, req.(*ListCatalogSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_GetCatalogSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCatalogSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).GetCatalogSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_GetCatalogSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).GetCatalogSkill(ctx, req.(*GetCatalogSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_GetCatalogSkillManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCatalogSkillManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).GetCatalogSkillManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_GetCatalogSkillManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).GetCatalogSkillManifest(ctx, req.(*GetCatalogSkillManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_DownloadCatalogSkillVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadSkillVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).DownloadCatalogSkillVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_DownloadCatalogSkillVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).DownloadCatalogSkillVersion(ctx, req.(*DownloadSkillVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SkillService_ServiceDesc is the grpc.ServiceDesc for SkillService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkillService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.skill.v1.SkillService",
	HandlerType: (*SkillServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSkill",
			Handler:    _SkillService_CreateSkill_Handler,
		},
		{
			MethodName: "UpdateSkill",
			Handler:    _SkillService_UpdateSkill_Handler,
		},
		{
			MethodName: "ListSkills",
			Handler:    _SkillService_ListSkills_Handler,
		},
		{
			MethodName: "GetSkill",
			Handler:    _SkillService_GetSkill_Handler,
		},
		{
			MethodName: "DeleteSkill",
			Handler:    _SkillService_DeleteSkill_Handler,
		},
		{
			MethodName: "UploadSkillPackage",
			Handler:    _SkillService_UploadSkillPackage_Handler,
		},
		{
			MethodName: "ListSkillVersions",
			Handler:    _SkillService_ListSkillVersions_Handler,
		},
		{
			MethodName: "GetSkillVersion",
			Handler:    _SkillService_GetSkillVersion_Handler,
		},
		{
			MethodName: "SubmitSkillVersion",
			Handler:    _SkillService_SubmitSkillVersion_Handler,
		},
		{
			MethodName: "PublishSkillVersion",
			Handler:    _SkillService_PublishSkillVersion_Handler,
		},
		{
			MethodName: "ForcePublishSkillVersion",
			Handler:    _SkillService_ForcePublishSkillVersion_Handler,
		},
		{
			MethodName: "OnlineSkillVersion",
			Handler:    _SkillService_OnlineSkillVersion_Handler,
		},
		{
			MethodName: "OfflineSkillVersion",
			Handler:    _SkillService_OfflineSkillVersion_Handler,
		},
		{
			MethodName: "DownloadSkillVersion",
			Handler:    _SkillService_DownloadSkillVersion_Handler,
		},
		{
			MethodName: "ListSkillVersionFiles",
			Handler:    _SkillService_ListSkillVersionFiles_Handler,
		},
		{
			MethodName: "GetSkillVersionFile",
			Handler:    _SkillService_GetSkillVersionFile_Handler,
		},
		{
			MethodName: "CompareSkillVersions",
			Handler:    _SkillService_CompareSkillVersions_Handler,
		},
		{
			MethodName: "ListSkillShares",
			Handler:    _SkillService_ListSkillShares_Handler,
		},
		{
			MethodName: "CreateSkillShare",
			Handler:    _SkillService_CreateSkillShare_Handler,
		},
		{
			MethodName: "DeleteSkillShare",
			Handler:    _SkillService_DeleteSkillShare_Handler,
		},
		{
			MethodName: "ListCatalogSkills",
			Handler:    _SkillService_ListCatalogSkills_Handler,
		},
		{
			MethodName: "GetCatalogSkill",
			Handler:    _SkillService_GetCatalogSkill_Handler,
		},
		{
			MethodName: "GetCatalogSkillManifest",
			Handler:    _SkillService_GetCatalogSkillManifest_Handler,
		},
		{
			MethodName: "DownloadCatalogSkillVersion",
			Handler:    _SkillService_DownloadCatalogSkillVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skill/v1/skill.proto",
}
