// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: skill/v1/skill.proto

package skillv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Skill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Visibility    string                 `protobuf:"bytes,7,opt,name=visibility,proto3" json:"visibility,omitempty"`
	OwnerId       string                 `protobuf:"bytes,8,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,9,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,10,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,11,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceUri     string                 `protobuf:"bytes,12,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`
	ManifestJson  string                 `protobuf:"bytes,13,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	Tags          []string               `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_skill_v1_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{0}
}

func (x *Skill) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Skill) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Skill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Skill) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Skill) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Skill) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Skill) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Skill) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Skill) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Skill) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *Skill) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *Skill) GetManifestJson() string {
	if x != nil {
		return x.ManifestJson
	}
	return ""
}

func (x *Skill) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Skill) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Skill) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type CreateSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Visibility    string                 `protobuf:"bytes,6,opt,name=visibility,proto3" json:"visibility,omitempty"`
	OwnerId       string                 `protobuf:"bytes,7,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,8,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,9,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,10,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceUri     string                 `protobuf:"bytes,11,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`
	ManifestJson  string                 `protobuf:"bytes,12,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	Tags          []string               `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkillRequest) Reset() {
	*x = CreateSkillRequest{}
	mi := &file_skill_v1_skill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillRequest) ProtoMessage() {}

func (x *CreateSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillRequest.ProtoReflect.Descriptor instead.
func (*CreateSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSkillRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateSkillRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSkillRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateSkillRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateSkillRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *CreateSkillRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateSkillRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CreateSkillRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateSkillRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *CreateSkillRequest) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *CreateSkillRequest) GetManifestJson() string {
	if x != nil {
		return x.ManifestJson
	}
	return ""
}

func (x *CreateSkillRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UpdateSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Visibility    string                 `protobuf:"bytes,6,opt,name=visibility,proto3" json:"visibility,omitempty"`
	OwnerId       string                 `protobuf:"bytes,7,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,8,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,9,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,10,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceUri     string                 `protobuf:"bytes,11,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`
	ManifestJson  string                 `protobuf:"bytes,12,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	Tags          []string               `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSkillRequest) Reset() {
	*x = UpdateSkillRequest{}
	mi := &file_skill_v1_skill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSkillRequest) ProtoMessage() {}

func (x *UpdateSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSkillRequest.ProtoReflect.Descriptor instead.
func (*UpdateSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSkillRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdateSkillRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateSkillRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateSkillRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateSkillRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *UpdateSkillRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *UpdateSkillRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *UpdateSkillRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateSkillRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *UpdateSkillRequest) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *UpdateSkillRequest) GetManifestJson() string {
	if x != nil {
		return x.ManifestJson
	}
	return ""
}

func (x *UpdateSkillRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ListSkillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Q             string                 `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Visibility    string                 `protobuf:"bytes,5,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillsRequest) Reset() {
	*x = ListSkillsRequest{}
	mi := &file_skill_v1_skill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsRequest) ProtoMessage() {}

func (x *ListSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsRequest.ProtoReflect.Descriptor instead.
func (*ListSkillsRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{3}
}

func (x *ListSkillsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSkillsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListSkillsRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *ListSkillsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListSkillsRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type ListSkillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*Skill               `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillsResponse) Reset() {
	*x = ListSkillsResponse{}
	mi := &file_skill_v1_skill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsResponse) ProtoMessage() {}

func (x *ListSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsResponse.ProtoReflect.Descriptor instead.
func (*ListSkillsResponse) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{4}
}

func (x *ListSkillsResponse) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ListSkillsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillRequest) Reset() {
	*x = GetSkillRequest{}
	mi := &file_skill_v1_skill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillRequest) ProtoMessage() {}

func (x *GetSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillRequest.ProtoReflect.Descriptor instead.
func (*GetSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{5}
}

func (x *GetSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSkillRequest) Reset() {
	*x = DeleteSkillRequest{}
	mi := &file_skill_v1_skill_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkillRequest) ProtoMessage() {}

func (x *DeleteSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkillRequest.ProtoReflect.Descriptor instead.
func (*DeleteSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UploadSkillPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageBytes  []byte                 `protobuf:"bytes,1,opt,name=package_bytes,json=packageBytes,proto3" json:"package_bytes,omitempty"`
	Overwrite     bool                   `protobuf:"varint,2,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	TargetVersion string                 `protobuf:"bytes,3,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	CommitMsg     string                 `protobuf:"bytes,4,opt,name=commit_msg,json=commitMsg,proto3" json:"commit_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSkillPackageRequest) Reset() {
	*x = UploadSkillPackageRequest{}
	mi := &file_skill_v1_skill_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSkillPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSkillPackageRequest) ProtoMessage() {}

func (x *UploadSkillPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSkillPackageRequest.ProtoReflect.Descriptor instead.
func (*UploadSkillPackageRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{7}
}

func (x *UploadSkillPackageRequest) GetPackageBytes() []byte {
	if x != nil {
		return x.PackageBytes
	}
	return nil
}

func (x *UploadSkillPackageRequest) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

func (x *UploadSkillPackageRequest) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *UploadSkillPackageRequest) GetCommitMsg() string {
	if x != nil {
		return x.CommitMsg
	}
	return ""
}

type SkillVersion struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SkillName           string                 `protobuf:"bytes,2,opt,name=skill_name,json=skillName,proto3" json:"skill_name,omitempty"`
	Version             string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Status              string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Author              string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	CommitMsg           string                 `protobuf:"bytes,6,opt,name=commit_msg,json=commitMsg,proto3" json:"commit_msg,omitempty"`
	PublishPipelineInfo string                 `protobuf:"bytes,7,opt,name=publish_pipeline_info,json=publishPipelineInfo,proto3" json:"publish_pipeline_info,omitempty"`
	DownloadCount       int64                  `protobuf:"varint,8,opt,name=download_count,json=downloadCount,proto3" json:"download_count,omitempty"`
	Md5                 string                 `protobuf:"bytes,9,opt,name=md5,proto3" json:"md5,omitempty"`
	Sha256              string                 `protobuf:"bytes,10,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Revision            string                 `protobuf:"bytes,11,opt,name=revision,proto3" json:"revision,omitempty"`
	SizeBytes           int64                  `protobuf:"varint,12,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ManifestJson        string                 `protobuf:"bytes,13,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	CreateTime          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime          *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SkillVersion) Reset() {
	*x = SkillVersion{}
	mi := &file_skill_v1_skill_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillVersion) ProtoMessage() {}

func (x *SkillVersion) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillVersion.ProtoReflect.Descriptor instead.
func (*SkillVersion) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{8}
}

func (x *SkillVersion) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SkillVersion) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

func (x *SkillVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SkillVersion) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SkillVersion) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *SkillVersion) GetCommitMsg() string {
	if x != nil {
		return x.CommitMsg
	}
	return ""
}

func (x *SkillVersion) GetPublishPipelineInfo() string {
	if x != nil {
		return x.PublishPipelineInfo
	}
	return ""
}

func (x *SkillVersion) GetDownloadCount() int64 {
	if x != nil {
		return x.DownloadCount
	}
	return 0
}

func (x *SkillVersion) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *SkillVersion) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *SkillVersion) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *SkillVersion) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *SkillVersion) GetManifestJson() string {
	if x != nil {
		return x.ManifestJson
	}
	return ""
}

func (x *SkillVersion) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *SkillVersion) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type ListSkillVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillVersionsRequest) Reset() {
	*x = ListSkillVersionsRequest{}
	mi := &file_skill_v1_skill_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillVersionsRequest) ProtoMessage() {}

func (x *ListSkillVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListSkillVersionsRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{9}
}

func (x *ListSkillVersionsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListSkillVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*SkillVersion        `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillVersionsResponse) Reset() {
	*x = ListSkillVersionsResponse{}
	mi := &file_skill_v1_skill_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillVersionsResponse) ProtoMessage() {}

func (x *ListSkillVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListSkillVersionsResponse) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{10}
}

func (x *ListSkillVersionsResponse) GetVersions() []*SkillVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type GetSkillVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillVersionRequest) Reset() {
	*x = GetSkillVersionRequest{}
	mi := &file_skill_v1_skill_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillVersionRequest) ProtoMessage() {}

func (x *GetSkillVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillVersionRequest.ProtoReflect.Descriptor instead.
func (*GetSkillVersionRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{11}
}

func (x *GetSkillVersionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSkillVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type SkillVersionActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillVersionActionRequest) Reset() {
	*x = SkillVersionActionRequest{}
	mi := &file_skill_v1_skill_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillVersionActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillVersionActionRequest) ProtoMessage() {}

func (x *SkillVersionActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillVersionActionRequest.ProtoReflect.Descriptor instead.
func (*SkillVersionActionRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{12}
}

func (x *SkillVersionActionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SkillVersionActionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type DownloadSkillVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	IfNoneMatch   string                 `protobuf:"bytes,3,opt,name=if_none_match,json=ifNoneMatch,proto3" json:"if_none_match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadSkillVersionRequest) Reset() {
	*x = DownloadSkillVersionRequest{}
	mi := &file_skill_v1_skill_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadSkillVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadSkillVersionRequest) ProtoMessage() {}

func (x *DownloadSkillVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadSkillVersionRequest.ProtoReflect.Descriptor instead.
func (*DownloadSkillVersionRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{13}
}

func (x *DownloadSkillVersionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DownloadSkillVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DownloadSkillVersionRequest) GetIfNoneMatch() string {
	if x != nil {
		return x.IfNoneMatch
	}
	return ""
}

type SkillPackageDownload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillName     string                 `protobuf:"bytes,1,opt,name=skill_name,json=skillName,proto3" json:"skill_name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Etag          string                 `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	Md5           string                 `protobuf:"bytes,4,opt,name=md5,proto3" json:"md5,omitempty"`
	Sha256        string                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	NotModified   bool                   `protobuf:"varint,6,opt,name=not_modified,json=notModified,proto3" json:"not_modified,omitempty"`
	PackageBytes  []byte                 `protobuf:"bytes,7,opt,name=package_bytes,json=packageBytes,proto3" json:"package_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillPackageDownload) Reset() {
	*x = SkillPackageDownload{}
	mi := &file_skill_v1_skill_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillPackageDownload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillPackageDownload) ProtoMessage() {}

func (x *SkillPackageDownload) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillPackageDownload.ProtoReflect.Descriptor instead.
func (*SkillPackageDownload) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{14}
}

func (x *SkillPackageDownload) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

func (x *SkillPackageDownload) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SkillPackageDownload) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *SkillPackageDownload) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *SkillPackageDownload) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *SkillPackageDownload) GetNotModified() bool {
	if x != nil {
		return x.NotModified
	}
	return false
}

func (x *SkillPackageDownload) GetPackageBytes() []byte {
	if x != nil {
		return x.PackageBytes
	}
	return nil
}

type SkillFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SkillName     string                 `protobuf:"bytes,2,opt,name=skill_name,json=skillName,proto3" json:"skill_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Size          int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Binary        bool                   `protobuf:"varint,8,opt,name=binary,proto3" json:"binary,omitempty"`
	Content       string                 `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillFile) Reset() {
	*x = SkillFile{}
	mi := &file_skill_v1_skill_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillFile) ProtoMessage() {}

func (x *SkillFile) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillFile.ProtoReflect.Descriptor instead.
func (*SkillFile) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{15}
}

func (x *SkillFile) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SkillFile) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

func (x *SkillFile) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SkillFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SkillFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SkillFile) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SkillFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SkillFile) GetBinary() bool {
	if x != nil {
		return x.Binary
	}
	return false
}

func (x *SkillFile) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SkillFile) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *SkillFile) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type ListSkillVersionFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillVersionFilesRequest) Reset() {
	*x = ListSkillVersionFilesRequest{}
	mi := &file_skill_v1_skill_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillVersionFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillVersionFilesRequest) ProtoMessage() {}

func (x *ListSkillVersionFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillVersionFilesRequest.ProtoReflect.Descriptor instead.
func (*ListSkillVersionFilesRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{16}
}

func (x *ListSkillVersionFilesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListSkillVersionFilesRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ListSkillVersionFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*SkillFile           `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillVersionFilesResponse) Reset() {
	*x = ListSkillVersionFilesResponse{}
	mi := &file_skill_v1_skill_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillVersionFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillVersionFilesResponse) ProtoMessage() {}

func (x *ListSkillVersionFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillVersionFilesResponse.ProtoReflect.Descriptor instead.
func (*ListSkillVersionFilesResponse) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{17}
}

func (x *ListSkillVersionFilesResponse) GetFiles() []*SkillFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type GetSkillVersionFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillVersionFileRequest) Reset() {
	*x = GetSkillVersionFileRequest{}
	mi := &file_skill_v1_skill_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillVersionFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillVersionFileRequest) ProtoMessage() {}

func (x *GetSkillVersionFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillVersionFileRequest.ProtoReflect.Descriptor instead.
func (*GetSkillVersionFileRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{18}
}

func (x *GetSkillVersionFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSkillVersionFileRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetSkillVersionFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CompareSkillVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BaseVersion   string                 `protobuf:"bytes,2,opt,name=base_version,json=baseVersion,proto3" json:"base_version,omitempty"`
	TargetVersion string                 `protobuf:"bytes,3,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareSkillVersionsRequest) Reset() {
	*x = CompareSkillVersionsRequest{}
	mi := &file_skill_v1_skill_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareSkillVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareSkillVersionsRequest) ProtoMessage() {}

func (x *CompareSkillVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareSkillVersionsRequest.ProtoReflect.Descriptor instead.
func (*CompareSkillVersionsRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{19}
}

func (x *CompareSkillVersionsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompareSkillVersionsRequest) GetBaseVersion() string {
	if x != nil {
		return x.BaseVersion
	}
	return ""
}

func (x *CompareSkillVersionsRequest) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

type CompareSkillVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseVersion   string                 `protobuf:"bytes,1,opt,name=base_version,json=baseVersion,proto3" json:"base_version,omitempty"`
	TargetVersion string                 `protobuf:"bytes,2,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	BaseSkillMd   string                 `protobuf:"bytes,3,opt,name=base_skill_md,json=baseSkillMd,proto3" json:"base_skill_md,omitempty"`
	TargetSkillMd string                 `protobuf:"bytes,4,opt,name=target_skill_md,json=targetSkillMd,proto3" json:"target_skill_md,omitempty"`
	BaseFiles     []*SkillFile           `protobuf:"bytes,5,rep,name=base_files,json=baseFiles,proto3" json:"base_files,omitempty"`
	TargetFiles   []*SkillFile           `protobuf:"bytes,6,rep,name=target_files,json=targetFiles,proto3" json:"target_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareSkillVersionsResponse) Reset() {
	*x = CompareSkillVersionsResponse{}
	mi := &file_skill_v1_skill_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareSkillVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareSkillVersionsResponse) ProtoMessage() {}

func (x *CompareSkillVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareSkillVersionsResponse.ProtoReflect.Descriptor instead.
func (*CompareSkillVersionsResponse) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{20}
}

func (x *CompareSkillVersionsResponse) GetBaseVersion() string {
	if x != nil {
		return x.BaseVersion
	}
	return ""
}

func (x *CompareSkillVersionsResponse) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *CompareSkillVersionsResponse) GetBaseSkillMd() string {
	if x != nil {
		return x.BaseSkillMd
	}
	return ""
}

func (x *CompareSkillVersionsResponse) GetTargetSkillMd() string {
	if x != nil {
		return x.TargetSkillMd
	}
	return ""
}

func (x *CompareSkillVersionsResponse) GetBaseFiles() []*SkillFile {
	if x != nil {
		return x.BaseFiles
	}
	return nil
}

func (x *CompareSkillVersionsResponse) GetTargetFiles() []*SkillFile {
	if x != nil {
		return x.TargetFiles
	}
	return nil
}

type SkillShare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrantId       string                 `protobuf:"bytes,1,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	SubjectType   string                 `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	SubjectId     string                 `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	Actions       []string               `protobuf:"bytes,7,rep,name=actions,proto3" json:"actions,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,9,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillShare) Reset() {
	*x = SkillShare{}
	mi := &file_skill_v1_skill_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillShare) ProtoMessage() {}

func (x *SkillShare) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillShare.ProtoReflect.Descriptor instead.
func (*SkillShare) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{21}
}

func (x *SkillShare) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *SkillShare) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *SkillShare) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SkillShare) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *SkillShare) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *SkillShare) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SkillShare) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *SkillShare) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *SkillShare) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type ListSkillSharesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillSharesRequest) Reset() {
	*x = ListSkillSharesRequest{}
	mi := &file_skill_v1_skill_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillSharesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillSharesRequest) ProtoMessage() {}

func (x *ListSkillSharesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillSharesRequest.ProtoReflect.Descriptor instead.
func (*ListSkillSharesRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{22}
}

func (x *ListSkillSharesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListSkillSharesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shares        []*SkillShare          `protobuf:"bytes,1,rep,name=shares,proto3" json:"shares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillSharesResponse) Reset() {
	*x = ListSkillSharesResponse{}
	mi := &file_skill_v1_skill_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillSharesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillSharesResponse) ProtoMessage() {}

func (x *ListSkillSharesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillSharesResponse.ProtoReflect.Descriptor instead.
func (*ListSkillSharesResponse) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{23}
}

func (x *ListSkillSharesResponse) GetShares() []*SkillShare {
	if x != nil {
		return x.Shares
	}
	return nil
}

type CreateSkillShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SubjectType   string                 `protobuf:"bytes,2,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	SubjectId     string                 `protobuf:"bytes,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,4,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,5,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	Actions       []string               `protobuf:"bytes,7,rep,name=actions,proto3" json:"actions,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,8,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkillShareRequest) Reset() {
	*x = CreateSkillShareRequest{}
	mi := &file_skill_v1_skill_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkillShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillShareRequest) ProtoMessage() {}

func (x *CreateSkillShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillShareRequest.ProtoReflect.Descriptor instead.
func (*CreateSkillShareRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{24}
}

func (x *CreateSkillShareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSkillShareRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *CreateSkillShareRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *CreateSkillShareRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CreateSkillShareRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateSkillShareRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateSkillShareRequest) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *CreateSkillShareRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type DeleteSkillShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GrantId       string                 `protobuf:"bytes,2,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSkillShareRequest) Reset() {
	*x = DeleteSkillShareRequest{}
	mi := &file_skill_v1_skill_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSkillShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkillShareRequest) ProtoMessage() {}

func (x *DeleteSkillShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkillShareRequest.ProtoReflect.Descriptor instead.
func (*DeleteSkillShareRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteSkillShareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteSkillShareRequest) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

type ListCatalogSkillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Q             string                 `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogSkillsRequest) Reset() {
	*x = ListCatalogSkillsRequest{}
	mi := &file_skill_v1_skill_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogSkillsRequest) ProtoMessage() {}

func (x *ListCatalogSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogSkillsRequest.ProtoReflect.Descriptor instead.
func (*ListCatalogSkillsRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{26}
}

func (x *ListCatalogSkillsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCatalogSkillsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListCatalogSkillsRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

type ListCatalogSkillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*Skill               `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogSkillsResponse) Reset() {
	*x = ListCatalogSkillsResponse{}
	mi := &file_skill_v1_skill_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogSkillsResponse) ProtoMessage() {}

func (x *ListCatalogSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogSkillsResponse.ProtoReflect.Descriptor instead.
func (*ListCatalogSkillsResponse) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{27}
}

func (x *ListCatalogSkillsResponse) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ListCatalogSkillsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetCatalogSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogSkillRequest) Reset() {
	*x = GetCatalogSkillRequest{}
	mi := &file_skill_v1_skill_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogSkillRequest) ProtoMessage() {}

func (x *GetCatalogSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogSkillRequest.ProtoReflect.Descriptor instead.
func (*GetCatalogSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{28}
}

func (x *GetCatalogSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCatalogSkillManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IfNoneMatch   string                 `protobuf:"bytes,2,opt,name=if_none_match,json=ifNoneMatch,proto3" json:"if_none_match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogSkillManifestRequest) Reset() {
	*x = GetCatalogSkillManifestRequest{}
	mi := &file_skill_v1_skill_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogSkillManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogSkillManifestRequest) ProtoMessage() {}

func (x *GetCatalogSkillManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogSkillManifestRequest.ProtoReflect.Descriptor instead.
func (*GetCatalogSkillManifestRequest) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{29}
}

func (x *GetCatalogSkillManifestRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCatalogSkillManifestRequest) GetIfNoneMatch() string {
	if x != nil {
		return x.IfNoneMatch
	}
	return ""
}

type SkillManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillName     string                 `protobuf:"bytes,1,opt,name=skill_name,json=skillName,proto3" json:"skill_name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Etag          string                 `protobuf:"bytes,4,opt,name=etag,proto3" json:"etag,omitempty"`
	Md5           string                 `protobuf:"bytes,5,opt,name=md5,proto3" json:"md5,omitempty"`
	Sha256        string                 `protobuf:"bytes,6,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Revision      string                 `protobuf:"bytes,7,opt,name=revision,proto3" json:"revision,omitempty"`
	ManifestJson  string                 `protobuf:"bytes,8,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	Files         []*SkillFile           `protobuf:"bytes,9,rep,name=files,proto3" json:"files,omitempty"`
	NotModified   bool                   `protobuf:"varint,10,opt,name=not_modified,json=notModified,proto3" json:"not_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillManifest) Reset() {
	*x = SkillManifest{}
	mi := &file_skill_v1_skill_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillManifest) ProtoMessage() {}

func (x *SkillManifest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_v1_skill_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillManifest.ProtoReflect.Descriptor instead.
func (*SkillManifest) Descriptor() ([]byte, []int) {
	return file_skill_v1_skill_proto_rawDescGZIP(), []int{30}
}

func (x *SkillManifest) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

func (x *SkillManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SkillManifest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SkillManifest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *SkillManifest) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *SkillManifest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *SkillManifest) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *SkillManifest) GetManifestJson() string {
	if x != nil {
		return x.ManifestJson
	}
	return ""
}

func (x *SkillManifest) GetFiles() []*SkillFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *SkillManifest) GetNotModified() bool {
	if x != nil {
		return x.NotModified
	}
	return false
}

var File_skill_v1_skill_proto protoreflect.FileDescriptor

const file_skill_v1_skill_proto_rawDesc = "" +
	"\n" +
	"\x14skill/v1/skill.proto\x12\fapi.skill.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x04\n" +
	"\x05Skill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"visibility\x18\a \x01(\tR\n" +
	"visibility\x12\x19\n" +
	"\bowner_id\x18\b \x01(\tR\aownerId\x12\x15\n" +
	"\x06org_id\x18\t \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"project_id\x18\n" +
	" \x01(\tR\tprojectId\x12\x1f\n" +
	"\vsource_type\x18\v \x01(\tR\n" +
	"sourceType\x12\x1d\n" +
	"\n" +
	"source_uri\x18\f \x01(\tR\tsourceUri\x12#\n" +
	"\rmanifest_json\x18\r \x01(\tR\fmanifestJson\x12\x12\n" +
	"\x04tags\x18\x0e \x03(\tR\x04tags\x12;\n" +
	"\vcreate_time\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"\x8e\x03\n" +
	"\x12CreateSkillRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"visibility\x18\x06 \x01(\tR\n" +
	"visibility\x12\x19\n" +
	"\bowner_id\x18\a \x01(\tR\aownerId\x12\x15\n" +
	"\x06org_id\x18\b \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"project_id\x18\t \x01(\tR\tprojectId\x12\x1f\n" +
	"\vsource_type\x18\n" +
	" \x01(\tR\n" +
	"sourceType\x12\x1d\n" +
	"\n" +
	"source_uri\x18\v \x01(\tR\tsourceUri\x12#\n" +
	"\rmanifest_json\x18\f \x01(\tR\fmanifestJson\x12\x12\n" +
	"\x04tags\x18\r \x03(\tR\x04tags\"\x8e\x03\n" +
	"\x12UpdateSkillRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"visibility\x18\x06 \x01(\tR\n" +
	"visibility\x12\x19\n" +
	"\bowner_id\x18\a \x01(\tR\aownerId\x12\x15\n" +
	"\x06org_id\x18\b \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"project_id\x18\t \x01(\tR\tprojectId\x12\x1f\n" +
	"\vsource_type\x18\n" +
	" \x01(\tR\n" +
	"sourceType\x12\x1d\n" +
	"\n" +
	"source_uri\x18\v \x01(\tR\tsourceUri\x12#\n" +
	"\rmanifest_json\x18\f \x01(\tR\fmanifestJson\x12\x12\n" +
	"\x04tags\x18\r \x03(\tR\x04tags\"\x95\x01\n" +
	"\x11ListSkillsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\f\n" +
	"\x01q\x18\x03 \x01(\tR\x01q\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"visibility\x18\x05 \x01(\tR\n" +
	"visibility\"i\n" +
	"\x12ListSkillsResponse\x12+\n" +
	"\x06skills\x18\x01 \x03(\v2\x13.api.skill.v1.SkillR\x06skills\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"*\n" +
	"\x0fGetSkillRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"-\n" +
	"\x12DeleteSkillRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"\xa9\x01\n" +
	"\x19UploadSkillPackageRequest\x12(\n" +
	"\rpackage_bytes\x18\x01 \x01(\fB\x03\xe0A\x02R\fpackageBytes\x12\x1c\n" +
	"\toverwrite\x18\x02 \x01(\bR\toverwrite\x12%\n" +
	"\x0etarget_version\x18\x03 \x01(\tR\rtargetVersion\x12\x1d\n" +
	"\n" +
	"commit_msg\x18\x04 \x01(\tR\tcommitMsg\"\x85\x04\n" +
	"\fSkillVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"skill_name\x18\x02 \x01(\tR\tskillName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x1d\n" +
	"\n" +
	"commit_msg\x18\x06 \x01(\tR\tcommitMsg\x122\n" +
	"\x15publish_pipeline_info\x18\a \x01(\tR\x13publishPipelineInfo\x12%\n" +
	"\x0edownload_count\x18\b \x01(\x03R\rdownloadCount\x12\x10\n" +
	"\x03md5\x18\t \x01(\tR\x03md5\x12\x16\n" +
	"\x06sha256\x18\n" +
	" \x01(\tR\x06sha256\x12\x1a\n" +
	"\brevision\x18\v \x01(\tR\brevision\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\f \x01(\x03R\tsizeBytes\x12#\n" +
	"\rmanifest_json\x18\r \x01(\tR\fmanifestJson\x12;\n" +
	"\vcreate_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"3\n" +
	"\x18ListSkillVersionsRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"S\n" +
	"\x19ListSkillVersionsResponse\x126\n" +
	"\bversions\x18\x01 \x03(\v2\x1a.api.skill.v1.SkillVersionR\bversions\"P\n" +
	"\x16GetSkillVersionRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\tB\x03\xe0A\x02R\aversion\"S\n" +
	"\x19SkillVersionActionRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\tB\x03\xe0A\x02R\aversion\"y\n" +
	"\x1bDownloadSkillVersionRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\tB\x03\xe0A\x02R\aversion\x12\"\n" +
	"\rif_none_match\x18\x03 \x01(\tR\vifNoneMatch\"\xd5\x01\n" +
	"\x14SkillPackageDownload\x12\x1d\n" +
	"\n" +
	"skill_name\x18\x01 \x01(\tR\tskillName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04etag\x18\x03 \x01(\tR\x04etag\x12\x10\n" +
	"\x03md5\x18\x04 \x01(\tR\x03md5\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\x12!\n" +
	"\fnot_modified\x18\x06 \x01(\bR\vnotModified\x12#\n" +
	"\rpackage_bytes\x18\a \x01(\fR\fpackageBytes\"\xd0\x02\n" +
	"\tSkillFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"skill_name\x18\x02 \x01(\tR\tskillName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\x12\x16\n" +
	"\x06binary\x18\b \x01(\bR\x06binary\x12\x18\n" +
	"\acontent\x18\t \x01(\tR\acontent\x12;\n" +
	"\vcreate_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"V\n" +
	"\x1cListSkillVersionFilesRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\tB\x03\xe0A\x02R\aversion\"N\n" +
	"\x1dListSkillVersionFilesResponse\x12-\n" +
	"\x05files\x18\x01 \x03(\v2\x17.api.skill.v1.SkillFileR\x05files\"m\n" +
	"\x1aGetSkillVersionFileRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\tB\x03\xe0A\x02R\aversion\x12\x17\n" +
	"\x04path\x18\x03 \x01(\tB\x03\xe0A\x02R\x04path\"\x8a\x01\n" +
	"\x1bCompareSkillVersionsRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12&\n" +
	"\fbase_version\x18\x02 \x01(\tB\x03\xe0A\x02R\vbaseVersion\x12*\n" +
	"\x0etarget_version\x18\x03 \x01(\tB\x03\xe0A\x02R\rtargetVersion\"\xa8\x02\n" +
	"\x1cCompareSkillVersionsResponse\x12!\n" +
	"\fbase_version\x18\x01 \x01(\tR\vbaseVersion\x12%\n" +
	"\x0etarget_version\x18\x02 \x01(\tR\rtargetVersion\x12\"\n" +
	"\rbase_skill_md\x18\x03 \x01(\tR\vbaseSkillMd\x12&\n" +
	"\x0ftarget_skill_md\x18\x04 \x01(\tR\rtargetSkillMd\x126\n" +
	"\n" +
	"base_files\x18\x05 \x03(\v2\x17.api.skill.v1.SkillFileR\tbaseFiles\x12:\n" +
	"\ftarget_files\x18\x06 \x03(\v2\x17.api.skill.v1.SkillFileR\vtargetFiles\"\x91\x02\n" +
	"\n" +
	"SkillShare\x12\x19\n" +
	"\bgrant_id\x18\x01 \x01(\tR\agrantId\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12!\n" +
	"\fsubject_type\x18\x04 \x01(\tR\vsubjectType\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tR\tsubjectId\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\x18\n" +
	"\aactions\x18\a \x03(\tR\aactions\x12\x1d\n" +
	"\n" +
	"created_by\x18\b \x01(\tR\tcreatedBy\x12#\n" +
	"\rmetadata_json\x18\t \x01(\tR\fmetadataJson\"1\n" +
	"\x16ListSkillSharesRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"K\n" +
	"\x17ListSkillSharesResponse\x120\n" +
	"\x06shares\x18\x01 \x03(\v2\x18.api.skill.v1.SkillShareR\x06shares\"\x82\x02\n" +
	"\x17CreateSkillShareRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12&\n" +
	"\fsubject_type\x18\x02 \x01(\tB\x03\xe0A\x02R\vsubjectType\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\tR\tsubjectId\x12\x15\n" +
	"\x06org_id\x18\x04 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x05 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\x18\n" +
	"\aactions\x18\a \x03(\tR\aactions\x12#\n" +
	"\rmetadata_json\x18\b \x01(\tR\fmetadataJson\"R\n" +
	"\x17DeleteSkillShareRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12\x1e\n" +
	"\bgrant_id\x18\x02 \x01(\tB\x03\xe0A\x02R\agrantId\"d\n" +
	"\x18ListCatalogSkillsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\f\n" +
	"\x01q\x18\x03 \x01(\tR\x01q\"p\n" +
	"\x19ListCatalogSkillsResponse\x12+\n" +
	"\x06skills\x18\x01 \x03(\v2\x13.api.skill.v1.SkillR\x06skills\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"1\n" +
	"\x16GetCatalogSkillRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"]\n" +
	"\x1eGetCatalogSkillManifestRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12\"\n" +
	"\rif_none_match\x18\x02 \x01(\tR\vifNoneMatch\"\xb1\x02\n" +
	"\rSkillManifest\x12\x1d\n" +
	"\n" +
	"skill_name\x18\x01 \x01(\tR\tskillName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04etag\x18\x04 \x01(\tR\x04etag\x12\x10\n" +
	"\x03md5\x18\x05 \x01(\tR\x03md5\x12\x16\n" +
	"\x06sha256\x18\x06 \x01(\tR\x06sha256\x12\x1a\n" +
	"\brevision\x18\a \x01(\tR\brevision\x12#\n" +
	"\rmanifest_json\x18\b \x01(\tR\fmanifestJson\x12-\n" +
	"\x05files\x18\t \x03(\v2\x17.api.skill.v1.SkillFileR\x05files\x12!\n" +
	"\fnot_modified\x18\n" +
	" \x01(\bR\vnotModified2\x9a\x1a\n" +
	"\fSkillService\x12a\n" +
	"\vCreateSkill\x12 .api.skill.v1.CreateSkillRequest\x1a\x13.api.skill.v1.Skill\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v3/aihub/skills\x12h\n" +
	"\vUpdateSkill\x12 .api.skill.v1.UpdateSkillRequest\x1a\x13.api.skill.v1.Skill\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/v3/aihub/skills/{name}\x12i\n" +
	"\n" +
	"ListSkills\x12\x1f.api.skill.v1.ListSkillsRequest\x1a .api.skill.v1.ListSkillsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v3/aihub/skills\x12_\n" +
	"\bGetSkill\x12\x1d.api.skill.v1.GetSkillRequest\x1a\x13.api.skill.v1.Skill\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v3/aihub/skills/{name}\x12h\n" +
	"\vDeleteSkill\x12 .api.skill.v1.DeleteSkillRequest\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/v3/aihub/skills/{name}\x12}\n" +
	"\x12UploadSkillPackage\x12'.api.skill.v1.UploadSkillPackageRequest\x1a\x1a.api.skill.v1.SkillVersion\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v3/aihub/skills:upload\x12\x8e\x01\n" +
	"\x11ListSkillVersions\x12&.api.skill.v1.ListSkillVersionsRequest\x1a'.api.skill.v1.ListSkillVersionsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v3/aihub/skills/{name}/versions\x12\x87\x01\n" +
	"\x0fGetSkillVersion\x12$.api.skill.v1.GetSkillVersionRequest\x1a\x1a.api.skill.v1.SkillVersion\"2\x82\xd3\xe4\x93\x02,\x12*/v3/aihub/skills/{name}/versions/{version}\x12\x97\x01\n" +
	"\x12SubmitSkillVersion\x12'.api.skill.v1.SkillVersionActionRequest\x1a\x1a.api.skill.v1.SkillVersion\"<\x82\xd3\xe4\x93\x026:\x01*\"1/v3/aihub/skills/{name}/versions/{version}:submit\x12\x99\x01\n" +
	"\x13PublishSkillVersion\x12'.api.skill.v1.SkillVersionActionRequest\x1a\x1a.api.skill.v1.SkillVersion\"=\x82\xd3\xe4\x93\x027:\x01*\"2/v3/aihub/skills/{name}/versions/{version}:publish\x12\xa4\x01\n" +
	"\x18ForcePublishSkillVersion\x12'.api.skill.v1.SkillVersionActionRequest\x1a\x1a.api.skill.v1.SkillVersion\"C\x82\xd3\xe4\x93\x02=:\x01*\"8/v3/aihub/skills/{name}/versions/{version}:force-publish\x12\x97\x01\n" +
	"\x12OnlineSkillVersion\x12'.api.skill.v1.SkillVersionActionRequest\x1a\x1a.api.skill.v1.SkillVersion\"<\x82\xd3\xe4\x93\x026:\x01*\"1/v3/aihub/skills/{name}/versions/{version}:online\x12\x99\x01\n" +
	"\x13OfflineSkillVersion\x12'.api.skill.v1.SkillVersionActionRequest\x1a\x1a.api.skill.v1.SkillVersion\"=\x82\xd3\xe4\x93\x027:\x01*\"2/v3/aihub/skills/{name}/versions/{version}:offline\x12\xa2\x01\n" +
	"\x14DownloadSkillVersion\x12).api.skill.v1.DownloadSkillVersionRequest\x1a\".api.skill.v1.SkillPackageDownload\";\x82\xd3\xe4\x93\x025\x123/v3/aihub/skills/{name}/versions/{version}/download\x12\xaa\x01\n" +
	"\x15ListSkillVersionFiles\x12*.api.skill.v1.ListSkillVersionFilesRequest\x1a+.api.skill.v1.ListSkillVersionFilesResponse\"8\x82\xd3\xe4\x93\x022\x120/v3/aihub/skills/{name}/versions/{version}/files\x12\x91\x01\n" +
	"\x13GetSkillVersionFile\x12(.api.skill.v1.GetSkillVersionFileRequest\x1a\x17.api.skill.v1.SkillFile\"7\x82\xd3\xe4\x93\x021\x12//v3/aihub/skills/{name}/versions/{version}/file\x12\x96\x01\n" +
	"\x14CompareSkillVersions\x12).api.skill.v1.CompareSkillVersionsRequest\x1a*.api.skill.v1.CompareSkillVersionsResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v3/aihub/skills/{name}/compare\x12\x86\x01\n" +
	"\x0fListSkillShares\x12$.api.skill.v1.ListSkillSharesRequest\x1a%.api.skill.v1.ListSkillSharesResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v3/aihub/skills/{name}/shares\x12~\n" +
	"\x10CreateSkillShare\x12%.api.skill.v1.CreateSkillShareRequest\x1a\x18.api.skill.v1.SkillShare\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v3/aihub/skills/{name}/shares\x12\x84\x01\n" +
	"\x10DeleteSkillShare\x12%.api.skill.v1.DeleteSkillShareRequest\x1a\x16.google.protobuf.Empty\"1\x82\xd3\xe4\x93\x02+*)/v3/aihub/skills/{name}/shares/{grant_id}\x12\x86\x01\n" +
	"\x11ListCatalogSkills\x12&.api.skill.v1.ListCatalogSkillsRequest\x1a'.api.skill.v1.ListCatalogSkillsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v3/aihub/catalog/skills\x12u\n" +
	"\x0fGetCatalogSkill\x12$.api.skill.v1.GetCatalogSkillRequest\x1a\x13.api.skill.v1.Skill\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v3/aihub/catalog/skills/{name}\x12\x96\x01\n" +
	"\x17GetCatalogSkillManifest\x12,.api.skill.v1.GetCatalogSkillManifestRequest\x1a\x1b.api.skill.v1.SkillManifest\"0\x82\xd3\xe4\x93\x02*\x12(/v3/aihub/catalog/skills/{name}/manifest\x12\xb1\x01\n" +
	"\x1bDownloadCatalogSkillVersion\x12).api.skill.v1.DownloadSkillVersionRequest\x1a\".api.skill.v1.SkillPackageDownload\"C\x82\xd3\xe4\x93\x02=\x12;/v3/aihub/catalog/skills/{name}/versions/{version}/downloadB\x93\x01\n" +
	"\x10com.api.skill.v1B\n" +
	"SkillProtoP\x01Z!aisphere-hub/api/skill/v1;skillv1\xa2\x02\x03ASX\xaa\x02\fApi.Skill.V1\xca\x02\fApi\\Skill\\V1\xe2\x02\x18Api\\Skill\\V1\\GPBMetadata\xea\x02\x0eApi::Skill::V1b\x06proto3"

var (
	file_skill_v1_skill_proto_rawDescOnce sync.Once
	file_skill_v1_skill_proto_rawDescData []byte
)

func file_skill_v1_skill_proto_rawDescGZIP() []byte {
	file_skill_v1_skill_proto_rawDescOnce.Do(func() {
		file_skill_v1_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skill_v1_skill_proto_rawDesc), len(file_skill_v1_skill_proto_rawDesc)))
	})
	return file_skill_v1_skill_proto_rawDescData
}

var file_skill_v1_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_skill_v1_skill_proto_goTypes = []any{
	(*Skill)(nil),                          // 0: api.skill.v1.Skill
	(*CreateSkillRequest)(nil),             // 1: api.skill.v1.CreateSkillRequest
	(*UpdateSkillRequest)(nil),             // 2: api.skill.v1.UpdateSkillRequest
	(*ListSkillsRequest)(nil),              // 3: api.skill.v1.ListSkillsRequest
	(*ListSkillsResponse)(nil),             // 4: api.skill.v1.ListSkillsResponse
	(*GetSkillRequest)(nil),                // 5: api.skill.v1.GetSkillRequest
	(*DeleteSkillRequest)(nil),             // 6: api.skill.v1.DeleteSkillRequest
	(*UploadSkillPackageRequest)(nil),      // 7: api.skill.v1.UploadSkillPackageRequest
	(*SkillVersion)(nil),                   // 8: api.skill.v1.SkillVersion
	(*ListSkillVersionsRequest)(nil),       // 9: api.skill.v1.ListSkillVersionsRequest
	(*ListSkillVersionsResponse)(nil),      // 10: api.skill.v1.ListSkillVersionsResponse
	(*GetSkillVersionRequest)(nil),         // 11: api.skill.v1.GetSkillVersionRequest
	(*SkillVersionActionRequest)(nil),      // 12: api.skill.v1.SkillVersionActionRequest
	(*DownloadSkillVersionRequest)(nil),    // 13: api.skill.v1.DownloadSkillVersionRequest
	(*SkillPackageDownload)(nil),           // 14: api.skill.v1.SkillPackageDownload
	(*SkillFile)(nil),                      // 15: api.skill.v1.SkillFile
	(*ListSkillVersionFilesRequest)(nil),   // 16: api.skill.v1.ListSkillVersionFilesRequest
	(*ListSkillVersionFilesResponse)(nil),  // 17: api.skill.v1.ListSkillVersionFilesResponse
	(*GetSkillVersionFileRequest)(nil),     // 18: api.skill.v1.GetSkillVersionFileRequest
	(*CompareSkillVersionsRequest)(nil),    // 19: api.skill.v1.CompareSkillVersionsRequest
	(*CompareSkillVersionsResponse)(nil),   // 20: api.skill.v1.CompareSkillVersionsResponse
	(*SkillShare)(nil),                     // 21: api.skill.v1.SkillShare
	(*ListSkillSharesRequest)(nil),         // 22: api.skill.v1.ListSkillSharesRequest
	(*ListSkillSharesResponse)(nil),        // 23: api.skill.v1.ListSkillSharesResponse
	(*CreateSkillShareRequest)(nil),        // 24: api.skill.v1.CreateSkillShareRequest
	(*DeleteSkillShareRequest)(nil),        // 25: api.skill.v1.DeleteSkillShareRequest
	(*ListCatalogSkillsRequest)(nil),       // 26: api.skill.v1.ListCatalogSkillsRequest
	(*ListCatalogSkillsResponse)(nil),      // 27: api.skill.v1.ListCatalogSkillsResponse
	(*GetCatalogSkillRequest)(nil),         // 28: api.skill.v1.GetCatalogSkillRequest
	(*GetCatalogSkillManifestRequest)(nil), // 29: api.skill.v1.GetCatalogSkillManifestRequest
	(*SkillManifest)(nil),                  // 30: api.skill.v1.SkillManifest
	(*timestamppb.Timestamp)(nil),          // 31: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 32: google.protobuf.Empty
}
var file_skill_v1_skill_proto_depIdxs = []int32{
	31, // 0: api.skill.v1.Skill.create_time:type_name -> google.protobuf.Timestamp
	31, // 1: api.skill.v1.Skill.update_time:type_name -> google.protobuf.Timestamp
	0,  // 2: api.skill.v1.ListSkillsResponse.skills:type_name -> api.skill.v1.Skill
	31, // 3: api.skill.v1.SkillVersion.create_time:type_name -> google.protobuf.Timestamp
	31, // 4: api.skill.v1.SkillVersion.update_time:type_name -> google.protobuf.Timestamp
	8,  // 5: api.skill.v1.ListSkillVersionsResponse.versions:type_name -> api.skill.v1.SkillVersion
	31, // 6: api.skill.v1.SkillFile.create_time:type_name -> google.protobuf.Timestamp
	31, // 7: api.skill.v1.SkillFile.update_time:type_name -> google.protobuf.Timestamp
	15, // 8: api.skill.v1.ListSkillVersionFilesResponse.files:type_name -> api.skill.v1.SkillFile
	15, // 9: api.skill.v1.CompareSkillVersionsResponse.base_files:type_name -> api.skill.v1.SkillFile
	15, // 10: api.skill.v1.CompareSkillVersionsResponse.target_files:type_name -> api.skill.v1.SkillFile
	21, // 11: api.skill.v1.ListSkillSharesResponse.shares:type_name -> api.skill.v1.SkillShare
	0,  // 12: api.skill.v1.ListCatalogSkillsResponse.skills:type_name -> api.skill.v1.Skill
	15, // 13: api.skill.v1.SkillManifest.files:type_name -> api.skill.v1.SkillFile
	1,  // 14: api.skill.v1.SkillService.CreateSkill:input_type -> api.skill.v1.CreateSkillRequest
	2,  // 15: api.skill.v1.SkillService.UpdateSkill:input_type -> api.skill.v1.UpdateSkillRequest
	3,  // 16: api.skill.v1.SkillService.ListSkills:input_type -> api.skill.v1.ListSkillsRequest
	5,  // 17: api.skill.v1.SkillService.GetSkill:input_type -> api.skill.v1.GetSkillRequest
	6,  // 18: api.skill.v1.SkillService.DeleteSkill:input_type -> api.skill.v1.DeleteSkillRequest
	7,  // 19: api.skill.v1.SkillService.UploadSkillPackage:input_type -> api.skill.v1.UploadSkillPackageRequest
	9,  // 20: api.skill.v1.SkillService.ListSkillVersions:input_type -> api.skill.v1.ListSkillVersionsRequest
	11, // 21: api.skill.v1.SkillService.GetSkillVersion:input_type -> api.skill.v1.GetSkillVersionRequest
	12, // 22: api.skill.v1.SkillService.SubmitSkillVersion:input_type -> api.skill.v1.SkillVersionActionRequest
	12, // 23: api.skill.v1.SkillService.PublishSkillVersion:input_type -> api.skill.v1.SkillVersionActionRequest
	12, // 24: api.skill.v1.SkillService.ForcePublishSkillVersion:input_type -> api.skill.v1.SkillVersionActionRequest
	12, // 25: api.skill.v1.SkillService.OnlineSkillVersion:input_type -> api.skill.v1.SkillVersionActionRequest
	12, // 26: api.skill.v1.SkillService.OfflineSkillVersion:input_type -> api.skill.v1.SkillVersionActionRequest
	13, // 27: api.skill.v1.SkillService.DownloadSkillVersion:input_type -> api.skill.v1.DownloadSkillVersionRequest
	16, // 28: api.skill.v1.SkillService.ListSkillVersionFiles:input_type -> api.skill.v1.ListSkillVersionFilesRequest
	18, // 29: api.skill.v1.SkillService.GetSkillVersionFile:input_type -> api.skill.v1.GetSkillVersionFileRequest
	19, // 30: api.skill.v1.SkillService.CompareSkillVersions:input_type -> api.skill.v1.CompareSkillVersionsRequest
	22, // 31: api.skill.v1.SkillService.ListSkillShares:input_type -> api.skill.v1.ListSkillSharesRequest
	24, // 32: api.skill.v1.SkillService.CreateSkillShare:input_type -> api.skill.v1.CreateSkillShareRequest
	25, // 33: api.skill.v1.SkillService.DeleteSkillShare:input_type -> api.skill.v1.DeleteSkillShareRequest
	26, // 34: api.skill.v1.SkillService.ListCatalogSkills:input_type -> api.skill.v1.ListCatalogSkillsRequest
	28, // 35: api.skill.v1.SkillService.GetCatalogSkill:input_type -> api.skill.v1.GetCatalogSkillRequest
	29, // 36: api.skill.v1.SkillService.GetCatalogSkillManifest:input_type -> api.skill.v1.GetCatalogSkillManifestRequest
	13, // 37: api.skill.v1.SkillService.DownloadCatalogSkillVersion:input_type -> api.skill.v1.DownloadSkillVersionRequest
	0,  // 38: api.skill.v1.SkillService.CreateSkill:output_type -> api.skill.v1.Skill
	0,  // 39: api.skill.v1.SkillService.UpdateSkill:output_type -> api.skill.v1.Skill
	4,  // 40: api.skill.v1.SkillService.ListSkills:output_type -> api.skill.v1.ListSkillsResponse
	0,  // 41: api.skill.v1.SkillService.GetSkill:output_type -> api.skill.v1.Skill
	32, // 42: api.skill.v1.SkillService.DeleteSkill:output_type -> google.protobuf.Empty
	8,  // 43: api.skill.v1.SkillService.UploadSkillPackage:output_type -> api.skill.v1.SkillVersion
	10, // 44: api.skill.v1.SkillService.ListSkillVersions:output_type -> api.skill.v1.ListSkillVersionsResponse
	8,  // 45: api.skill.v1.SkillService.GetSkillVersion:output_type -> api.skill.v1.SkillVersion
	8,  // 46: api.skill.v1.SkillService.SubmitSkillVersion:output_type -> api.skill.v1.SkillVersion
	8,  // 47: api.skill.v1.SkillService.PublishSkillVersion:output_type -> api.skill.v1.SkillVersion
	8,  // 48: api.skill.v1.SkillService.ForcePublishSkillVersion:output_type -> api.skill.v1.SkillVersion
	8,  // 49: api.skill.v1.SkillService.OnlineSkillVersion:output_type -> api.skill.v1.SkillVersion
	8,  // 50: api.skill.v1.SkillService.OfflineSkillVersion:output_type -> api.skill.v1.SkillVersion
	14, // 51: api.skill.v1.SkillService.DownloadSkillVersion:output_type -> api.skill.v1.SkillPackageDownload
	17, // 52: api.skill.v1.SkillService.ListSkillVersionFiles:output_type -> api.skill.v1.ListSkillVersionFilesResponse
	15, // 53: api.skill.v1.SkillService.GetSkillVersionFile:output_type -> api.skill.v1.SkillFile
	20, // 54: api.skill.v1.SkillService.CompareSkillVersions:output_type -> api.skill.v1.CompareSkillVersionsResponse
	23, // 55: api.skill.v1.SkillService.ListSkillShares:output_type -> api.skill.v1.ListSkillSharesResponse
	21, // 56: api.skill.v1.SkillService.CreateSkillShare:output_type -> api.skill.v1.SkillShare
	32, // 57: api.skill.v1.SkillService.DeleteSkillShare:output_type -> google.protobuf.Empty
	27, // 58: api.skill.v1.SkillService.ListCatalogSkills:output_type -> api.skill.v1.ListCatalogSkillsResponse
	0,  // 59: api.skill.v1.SkillService.GetCatalogSkill:output_type -> api.skill.v1.Skill
	30, // 60: api.skill.v1.SkillService.GetCatalogSkillManifest:output_type -> api.skill.v1.SkillManifest
	14, // 61: api.skill.v1.SkillService.DownloadCatalogSkillVersion:output_type -> api.skill.v1.SkillPackageDownload
	38, // [38:62] is the sub-list for method output_type
	14, // [14:38] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_skill_v1_skill_proto_init() }
func file_skill_v1_skill_proto_init() {
	if File_skill_v1_skill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skill_v1_skill_proto_rawDesc), len(file_skill_v1_skill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_skill_v1_skill_proto_goTypes,
		DependencyIndexes: file_skill_v1_skill_proto_depIdxs,
		MessageInfos:      file_skill_v1_skill_proto_msgTypes,
	}.Build()
	File_skill_v1_skill_proto = out.File
	file_skill_v1_skill_proto_goTypes = nil
	file_skill_v1_skill_proto_depIdxs = nil
}
