// aisphere-hub backend health service definition.
//
// This is a Phase 1 smoke-test proto. It exists to:
//   1. Verify the buf/protoc toolchain works on the developer's machine.
//   2. Give the kratos HTTP server at least one non-/livez route to exercise
//      the middleware chain.
//
// Once business modules start migrating (Phase 3+), each module gets its own
// proto under api/<module>/v1/<module>.proto. This health.proto can stay as
// a lightweight liveness/readiness complement to /livez and /readyz.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: health/v1/health.proto

package healthv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional component name to check; empty means "all components".
	Component     string `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_health_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_health_v1_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall status: "ok" or "degraded".
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Unix timestamp (seconds) of the check.
	CheckedAt int64 `protobuf:"varint,2,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	// Per-component details, keyed by component name.
	Components    map[string]string `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_health_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_health_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetCheckedAt() int64 {
	if x != nil {
		return x.CheckedAt
	}
	return 0
}

func (x *HealthCheckResponse) GetComponents() map[string]string {
	if x != nil {
		return x.Components
	}
	return nil
}

var File_health_v1_health_proto protoreflect.FileDescriptor

const file_health_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x16health/v1/health.proto\x12\rapi.health.v1\x1a\x1cgoogle/api/annotations.proto\"2\n" +
	"\x12HealthCheckRequest\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\"\xdf\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x02 \x01(\x03R\tcheckedAt\x12R\n" +
	"\n" +
	"components\x18\x03 \x03(\v22.api.health.v1.HealthCheckResponse.ComponentsEntryR\n" +
	"components\x1a=\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012y\n" +
	"\rHealthService\x12h\n" +
	"\x05Check\x12!.api.health.v1.HealthCheckRequest\x1a\".api.health.v1.HealthCheckResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v3/aihub/healthB\x9b\x01\n" +
	"\x11com.api.health.v1B\vHealthProtoP\x01Z#aisphere-hub/api/health/v1;healthv1\xa2\x02\x03AHX\xaa\x02\rApi.Health.V1\xca\x02\rApi\\Health\\V1\xe2\x02\x19Api\\Health\\V1\\GPBMetadata\xea\x02\x0fApi::Health::V1b\x06proto3"

var (
	file_health_v1_health_proto_rawDescOnce sync.Once
	file_health_v1_health_proto_rawDescData []byte
)

func file_health_v1_health_proto_rawDescGZIP() []byte {
	file_health_v1_health_proto_rawDescOnce.Do(func() {
		file_health_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_v1_health_proto_rawDesc), len(file_health_v1_health_proto_rawDesc)))
	})
	return file_health_v1_health_proto_rawDescData
}

var file_health_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_health_v1_health_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),  // 0: api.health.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 1: api.health.v1.HealthCheckResponse
	nil,                         // 2: api.health.v1.HealthCheckResponse.ComponentsEntry
}
var file_health_v1_health_proto_depIdxs = []int32{
	2, // 0: api.health.v1.HealthCheckResponse.components:type_name -> api.health.v1.HealthCheckResponse.ComponentsEntry
	0, // 1: api.health.v1.HealthService.Check:input_type -> api.health.v1.HealthCheckRequest
	1, // 2: api.health.v1.HealthService.Check:output_type -> api.health.v1.HealthCheckResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_health_v1_health_proto_init() }
func file_health_v1_health_proto_init() {
	if File_health_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_v1_health_proto_rawDesc), len(file_health_v1_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_health_v1_health_proto_goTypes,
		DependencyIndexes: file_health_v1_health_proto_depIdxs,
		MessageInfos:      file_health_v1_health_proto_msgTypes,
	}.Build()
	File_health_v1_health_proto = out.File
	file_health_v1_health_proto_goTypes = nil
	file_health_v1_health_proto_depIdxs = nil
}
