// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: health/v1/health.proto

package healthv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationHealthServiceCheck = "/api.health.v1.HealthService/Check"

type HealthServiceHTTPServer interface {
	// Check Check returns the current service health snapshot.
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
}

func RegisterHealthServiceHTTPServer(s *http.Server, srv HealthServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v3/aihub/health", _HealthService_Check0_HTTP_Handler(srv))
}

func _HealthService_Check0_HTTP_Handler(srv HealthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HealthCheckRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHealthServiceCheck)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Check(ctx, req.(*HealthCheckRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HealthCheckResponse)
		return ctx.Result(200, reply)
	}
}

type HealthServiceHTTPClient interface {
	// Check Check returns the current service health snapshot.
	Check(ctx context.Context, req *HealthCheckRequest, opts ...http.CallOption) (rsp *HealthCheckResponse, err error)
}

type HealthServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewHealthServiceHTTPClient(client *http.Client) HealthServiceHTTPClient {
	return &HealthServiceHTTPClientImpl{client}
}

// Check Check returns the current service health snapshot.
func (c *HealthServiceHTTPClientImpl) Check(ctx context.Context, in *HealthCheckRequest, opts ...http.CallOption) (*HealthCheckResponse, error) {
	var out HealthCheckResponse
	pattern := "/v3/aihub/health"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationHealthServiceCheck),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
