// Package service health module — HTTP handler + DTO↔DO conversion.
//
// This file follows the AGENTS.md layer contract:
//   - service imports both api (proto DTO) and biz (domain object).
//   - service does NOT import data.
//   - All DTO↔DO conversion happens here, never in biz or data.
//
// The handler implements the HealthServiceHTTPServer interface generated by
// protoc-gen-go-http from api/health/v1/health.proto.
//
// RegisterHTTPServer is the conventional hook that app.NewApp calls to mount
// this module's routes on the kratos HTTP server. Keeping the registration
// inside the service (not in app.go) means adding a new module requires
// ZERO changes to app.go — only the service's own file and the ProviderSet.

package service

import (
	"context"

	v1 "aisphere-hub/api/health/v1"
	"aisphere-hub/internal/biz"

	khttp "github.com/go-kratos/kratos/v3/transport/http"
)

// HealthService implements v1.HealthServiceHTTPServer.
//
// Note: kratos's protoc-gen-go-http does NOT generate an
// UnimplementedXxxHTTPServer struct (unlike protoc-gen-go-grpc). When a new
// RPC is added to the proto, the compiler will fail here until we implement
// the new method on HealthService — which is the desired behavior.
type HealthService struct {
	uc *biz.HealthUsecase
}

// NewHealthService constructs a HealthService.
func NewHealthService(uc *biz.HealthUsecase) *HealthService {
	return &HealthService{uc: uc}
}

// RegisterHTTPServer mounts HealthService routes on the kratos HTTP server.
// app.NewApp calls this for every migrated module.
func (s *HealthService) RegisterHTTPServer(srv *khttp.Server) {
	v1.RegisterHealthServiceHTTPServer(srv, s)
}

// Check handles GET /v3/aihub/health.
//
// The component filter in the request is currently advisory — we always return
// the full component list. A future iteration can filter the components map
// server-side if a specific component is requested.
func (s *HealthService) Check(ctx context.Context, req *v1.HealthCheckRequest) (*v1.HealthCheckResponse, error) {
	h, err := s.uc.Check(ctx)
	if err != nil {
		return nil, err
	}
	return healthDOToDTO(h), nil
}

// healthDOToDTO converts the biz.Health domain object to the proto DTO.
// Keep this function side-effect free and easy to test.
func healthDOToDTO(h *biz.Health) *v1.HealthCheckResponse {
	if h == nil {
		return &v1.HealthCheckResponse{Status: "unknown"}
	}
	resp := &v1.HealthCheckResponse{
		Status:     h.Status,
		CheckedAt:  h.CheckedAt.Unix(),
		Components: make(map[string]string, len(h.Components)),
	}
	for _, c := range h.Components {
		// Encode each component as "ok" or "fail: <error>" for compactness.
		// If you need structured per-component data, extend the proto with a
		// repeated Component message instead of a map<string,string>.
		if c.OK {
			resp.Components[c.Name] = "ok"
		} else {
			resp.Components[c.Name] = "fail: " + c.Error
		}
	}
	return resp
}
