apiVersion: v1
kind: ConfigMap
metadata:
  name: aisphere-hub-front-config
  namespace: aisphere
  labels:
    app: aisphere-hub-front
    service: hub-front
data:
  NEXT_PUBLIC_HUB_URL: ""
  NEXT_PUBLIC_AUTH_MODE: "gateway_oidc"
  NODE_ENV: "production"