// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"aisphere-hub/internal/biz"
	"aisphere-hub/internal/data"
	"aisphere-hub/internal/service"
	"context"
	"github.com/actionlab-ai/aisphere-kit/config"
	"github.com/actionlab-ai/aisphere-kit/starter"
)

// Injectors from wire.go:

// wireApp is the injector entry point. wire.Build receives every layer's
// ProviderSet plus a struct provider for AppDeps (so wire knows how to
// assemble the output struct from individual service providers).
//
// The signature is the contract app.NewApp relies on:
//
//	func(ctx, cfg *kitconfig.Config, rt *kitstarter.Runtime) (*AppDeps, func(), error)
//
// Adding a new module does NOT require touching this function — just append
// the constructor to the relevant ProviderSet in biz/data/service, add a
// field to AppDeps, and re-run `make wire`.
func wireApp(ctx context.Context, cfg *config.Config, rt *starter.Runtime) (*AppDeps, func(), error) {
	dataData, cleanup, err := data.NewRuntimeData(ctx, cfg, rt)
	if err != nil {
		return nil, nil, err
	}
	healthRepo := data.NewHealthRepo(dataData)
	healthUsecase := biz.NewHealthUsecase(healthRepo)
	healthService := service.NewHealthService(healthUsecase)
	authRepo := data.NewAuthRepo(dataData)
	guard := data.NewAccessGuard(dataData)
	authUsecase := biz.NewAuthUsecase(authRepo, guard)
	authService := service.NewAuthService(authUsecase)
	skillRepo, err := data.NewSkillRepo(dataData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	manager := data.NewPermissionManager(dataData)
	skillUsecase := biz.NewSkillUsecase(skillRepo, guard, manager)
	skillService := service.NewSkillService(skillUsecase)
	appDeps := &AppDeps{
		Health: healthService,
		Auth:   authService,
		Skill:  skillService,
	}
	return appDeps, func() {
		cleanup()
	}, nil
}
