// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: auth/v1/auth.proto

package authv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_LoginURL_FullMethodName  = "/api.auth.v1.AuthService/LoginURL"
	AuthService_Exchange_FullMethodName  = "/api.auth.v1.AuthService/Exchange"
	AuthService_Refresh_FullMethodName   = "/api.auth.v1.AuthService/Refresh"
	AuthService_LogoutURL_FullMethodName = "/api.auth.v1.AuthService/LogoutURL"
	AuthService_Me_FullMethodName        = "/api.auth.v1.AuthService/Me"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthService is the Casdoor-native authentication facade for AIHub.
//
// Hub does not issue or persist local tokens. Browser login, OAuth code
// exchange, refresh, and logout are delegated to Casdoor. API requests are
// authenticated by aisphere-kit-kratos middleware using Casdoor access tokens.
type AuthServiceClient interface {
	// LoginURL returns the Casdoor authorization URL as JSON for SPA/debug usage.
	// Browser users should prefer GET /v3/auth/login, which is registered as a
	// direct HTTP 302 route by the service implementation.
	LoginURL(ctx context.Context, in *LoginURLRequest, opts ...grpc.CallOption) (*LoginURLResponse, error)
	// Exchange exchanges an OAuth authorization code for Casdoor tokens.
	// HTTP JSON binding is implemented manually in internal/service/auth.go so
	// both snake_case (redirect_uri) and camelCase (redirectUri) clients work.
	Exchange(ctx context.Context, in *ExchangeRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	// Refresh refreshes a Casdoor access token.
	// HTTP JSON binding is implemented manually in internal/service/auth.go so
	// both snake_case (refresh_token) and camelCase (refreshToken) clients work.
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	// LogoutURL returns the Casdoor logout URL as JSON for SPA/debug usage.
	// Browser users can also call GET /v3/auth/logout for direct HTTP 302.
	LogoutURL(ctx context.Context, in *LogoutURLRequest, opts ...grpc.CallOption) (*LogoutURLResponse, error)
	// Me returns the current authenticated principal.
	Me(ctx context.Context, in *MeRequest, opts ...grpc.CallOption) (*MeResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) LoginURL(ctx context.Context, in *LoginURLRequest, opts ...grpc.CallOption) (*LoginURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginURLResponse)
	err := c.cc.Invoke(ctx, AuthService_LoginURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Exchange(ctx context.Context, in *ExchangeRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, AuthService_Exchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, AuthService_Refresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) LogoutURL(ctx context.Context, in *LogoutURLRequest, opts ...grpc.CallOption) (*LogoutURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutURLResponse)
	err := c.cc.Invoke(ctx, AuthService_LogoutURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Me(ctx context.Context, in *MeRequest, opts ...grpc.CallOption) (*MeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeResponse)
	err := c.cc.Invoke(ctx, AuthService_Me_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// AuthService is the Casdoor-native authentication facade for AIHub.
//
// Hub does not issue or persist local tokens. Browser login, OAuth code
// exchange, refresh, and logout are delegated to Casdoor. API requests are
// authenticated by aisphere-kit-kratos middleware using Casdoor access tokens.
type AuthServiceServer interface {
	// LoginURL returns the Casdoor authorization URL as JSON for SPA/debug usage.
	// Browser users should prefer GET /v3/auth/login, which is registered as a
	// direct HTTP 302 route by the service implementation.
	LoginURL(context.Context, *LoginURLRequest) (*LoginURLResponse, error)
	// Exchange exchanges an OAuth authorization code for Casdoor tokens.
	// HTTP JSON binding is implemented manually in internal/service/auth.go so
	// both snake_case (redirect_uri) and camelCase (redirectUri) clients work.
	Exchange(context.Context, *ExchangeRequest) (*TokenResponse, error)
	// Refresh refreshes a Casdoor access token.
	// HTTP JSON binding is implemented manually in internal/service/auth.go so
	// both snake_case (refresh_token) and camelCase (refreshToken) clients work.
	Refresh(context.Context, *RefreshRequest) (*TokenResponse, error)
	// LogoutURL returns the Casdoor logout URL as JSON for SPA/debug usage.
	// Browser users can also call GET /v3/auth/logout for direct HTTP 302.
	LogoutURL(context.Context, *LogoutURLRequest) (*LogoutURLResponse, error)
	// Me returns the current authenticated principal.
	Me(context.Context, *MeRequest) (*MeResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) LoginURL(context.Context, *LoginURLRequest) (*LoginURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginURL not implemented")
}
func (UnimplementedAuthServiceServer) Exchange(context.Context, *ExchangeRequest) (*TokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exchange not implemented")
}
func (UnimplementedAuthServiceServer) Refresh(context.Context, *RefreshRequest) (*TokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedAuthServiceServer) LogoutURL(context.Context, *LogoutURLRequest) (*LogoutURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LogoutURL not implemented")
}
func (UnimplementedAuthServiceServer) Me(context.Context, *MeRequest) (*MeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Me not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_LoginURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).LoginURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_LoginURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).LoginURL(ctx, req.(*LoginURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Exchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Exchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Exchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Exchange(ctx, req.(*ExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Refresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_LogoutURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).LogoutURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_LogoutURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).LogoutURL(ctx, req.(*LogoutURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Me_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Me(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Me_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Me(ctx, req.(*MeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.auth.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginURL",
			Handler:    _AuthService_LoginURL_Handler,
		},
		{
			MethodName: "Exchange",
			Handler:    _AuthService_Exchange_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _AuthService_Refresh_Handler,
		},
		{
			MethodName: "LogoutURL",
			Handler:    _AuthService_LogoutURL_Handler,
		},
		{
			MethodName: "Me",
			Handler:    _AuthService_Me_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/v1/auth.proto",
}
