// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: auth/v1/auth.proto

package authv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationAuthServiceLoginURL = "/api.auth.v1.AuthService/LoginURL"
const OperationAuthServiceLogoutURL = "/api.auth.v1.AuthService/LogoutURL"
const OperationAuthServiceMe = "/api.auth.v1.AuthService/Me"

type AuthServiceHTTPServer interface {
	// LoginURL LoginURL returns the Casdoor authorization URL as JSON for SPA/debug usage.
	// Browser users should prefer GET /v3/auth/login, which is registered as a
	// direct HTTP 302 route by the service implementation.
	LoginURL(context.Context, *LoginURLRequest) (*LoginURLResponse, error)
	// LogoutURL LogoutURL returns the Casdoor logout URL as JSON for SPA/debug usage.
	// Browser users can also call GET /v3/auth/logout for direct HTTP 302.
	LogoutURL(context.Context, *LogoutURLRequest) (*LogoutURLResponse, error)
	// Me Me returns the current authenticated principal.
	Me(context.Context, *MeRequest) (*MeResponse, error)
}

func RegisterAuthServiceHTTPServer(s *http.Server, srv AuthServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v3/auth/login-url", _AuthService_LoginURL0_HTTP_Handler(srv))
	r.Handle("GET", "/v3/auth/logout-url", _AuthService_LogoutURL0_HTTP_Handler(srv))
	r.Handle("GET", "/v3/auth/me", _AuthService_Me0_HTTP_Handler(srv))
}

func _AuthService_LoginURL0_HTTP_Handler(srv AuthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginURLRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthServiceLoginURL)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LoginURL(ctx, req.(*LoginURLRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginURLResponse)
		return ctx.Result(200, reply)
	}
}

func _AuthService_LogoutURL0_HTTP_Handler(srv AuthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LogoutURLRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthServiceLogoutURL)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LogoutURL(ctx, req.(*LogoutURLRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LogoutURLResponse)
		return ctx.Result(200, reply)
	}
}

func _AuthService_Me0_HTTP_Handler(srv AuthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthServiceMe)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Me(ctx, req.(*MeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MeResponse)
		return ctx.Result(200, reply)
	}
}

type AuthServiceHTTPClient interface {
	// LoginURL LoginURL returns the Casdoor authorization URL as JSON for SPA/debug usage.
	// Browser users should prefer GET /v3/auth/login, which is registered as a
	// direct HTTP 302 route by the service implementation.
	LoginURL(ctx context.Context, req *LoginURLRequest, opts ...http.CallOption) (rsp *LoginURLResponse, err error)
	// LogoutURL LogoutURL returns the Casdoor logout URL as JSON for SPA/debug usage.
	// Browser users can also call GET /v3/auth/logout for direct HTTP 302.
	LogoutURL(ctx context.Context, req *LogoutURLRequest, opts ...http.CallOption) (rsp *LogoutURLResponse, err error)
	// Me Me returns the current authenticated principal.
	Me(ctx context.Context, req *MeRequest, opts ...http.CallOption) (rsp *MeResponse, err error)
}

type AuthServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAuthServiceHTTPClient(client *http.Client) AuthServiceHTTPClient {
	return &AuthServiceHTTPClientImpl{client}
}

// LoginURL LoginURL returns the Casdoor authorization URL as JSON for SPA/debug usage.
// Browser users should prefer GET /v3/auth/login, which is registered as a
// direct HTTP 302 route by the service implementation.
func (c *AuthServiceHTTPClientImpl) LoginURL(ctx context.Context, in *LoginURLRequest, opts ...http.CallOption) (*LoginURLResponse, error) {
	var out LoginURLResponse
	pattern := "/v3/auth/login-url"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAuthServiceLoginURL),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LogoutURL LogoutURL returns the Casdoor logout URL as JSON for SPA/debug usage.
// Browser users can also call GET /v3/auth/logout for direct HTTP 302.
func (c *AuthServiceHTTPClientImpl) LogoutURL(ctx context.Context, in *LogoutURLRequest, opts ...http.CallOption) (*LogoutURLResponse, error) {
	var out LogoutURLResponse
	pattern := "/v3/auth/logout-url"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAuthServiceLogoutURL),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Me Me returns the current authenticated principal.
func (c *AuthServiceHTTPClientImpl) Me(ctx context.Context, in *MeRequest, opts ...http.CallOption) (*MeResponse, error) {
	var out MeResponse
	pattern := "/v3/auth/me"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAuthServiceMe),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
